### ISSUE TITLE
Create 'All Events' button on 'News & Events' page below the calendar block

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#1000]
Button should be based on style guide - https://app.frontify.com/document/35623

**Comment by bradnovation** [comment]
for reference - using this mock regarding the button https://projects.invisionapp.com/share/KB4R6KBD9#/screens/116357094

**Comment by jayappnovation** [comment]
BE done, Front end needed

**Comment by PeaceGeeksProjects** [comment]
Events page styled in #1202
