### ISSUE TITLE
Resources view needs to correspond to the mock

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#1001]
Need to add 'Featured' resources
Also need to add additional fields to general 'resouces'

**Comment by PeaceGeeks** [comment]
Resources theming got broken recently - see http://dev.amani-zen-theme.peacegeeks.org/resources or screenshot

<img width="1280" alt="screen shot 2016-01-08 at 9 02 24 am" src="https://cloud.githubusercontent.com/assets/2263033/12204003/943d0384-b5e6-11e5-8607-cb1d6ec48579.png">

**Comment by limage** [comment]
fixed! missing download button, that will be in separate ticket
https://github.com/PeaceGeeksSociety/amani/pull/1070

**Comment by akochlan** [comment]
Validated on dev. Resource view doesn't match mockups:

- missed label 'Filter'
- wrong order of buttons Apply and Reset.
- missed switch for layout beside FEATURED RESOURCES
- missed Download button.

**Comment by PeaceGeeksProjects** [comment]
duplicate of several detailed issues e.g. #1028
