### ISSUE TITLE
Copy under 'Get Involved' on Programs should be single spaced

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#1007]
http://dev.amani-zen-theme.peacegeeks.org/programs

**Comment by limage** [comment]
Done! Committed to Amani-zen-theme branch

**Comment by PeaceGeeks** [comment]
@limage - this is still displaying on dev as 1.5 spaced

**Comment by limage** [comment]
It looks fine. Please make a screenshot if it still not fixed.

**Comment by akochlan** [comment]
Validated on dev: http://dev.amani-zen-theme.peacegeeks.org/programs. Everything looks good under 'Get Involved'.

@PeaceGeeks Please, clarify what was the issue.

**Comment by PeaceGeeksProjects** [comment]
Looks fine now
