### ISSUE TITLE
Amani-Zen: Missing home button on the Header menu

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1015]
Home button needs to be added to the header menu 
![homebutton](https://cloud.githubusercontent.com/assets/15751109/11543402/3de9ba16-98f1-11e5-9108-d17c67349b4e.png)

**Comment by dannyzoujx** [comment]
@PeaceGeeks

**Comment by sheilaj** [comment]
The Home link is added to amani_administrator_get_main_menu_links(). For sites already installed, reset the default menu links for the main menu at /admin/configure-amani. The home link will then appear last and has to be manually dragged to the first position.

**Comment by PeaceGeeks** [comment]
Ready for testing upon deploy

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
