### ISSUE TITLE
Amani-Zen: Missing "Home" and "Login" buttons on the Footer menu

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1016]
Missing Home and Login buttons on the footer Menu.
![footerbutton](https://cloud.githubusercontent.com/assets/15751109/11543513/00445c10-98f2-11e5-9ef1-a469253751f9.png)

This is not listed on the Audit Doc. However, I had a discussion with Li. he mentioned that this requires a lot of code changes for the footer (2 columns to 3 columns). Need more confirmation on whether this change is needed.

**Comment by dannyzoujx** [comment]
@PeaceGeeks

**Comment by sheilaj** [comment]
The menu displayed in the footer is the same one as in the header (menu-amani-main-menu). I just added the Home link to the main menu. If I add the Login link, it will appear in the header as well as the footer. Do we want the possibility of displaying different links here? If so, we need a separate menu for the footer.

**Comment by PeaceGeeks** [comment]
Ready for theming @limage

**Comment by erica-scott** [comment]
This was attempted by adding a new menu for the footer links, which is very similar to the main menu but with a few additions. Originally, the main menu was being used for both the header and the footer, so it was not possible to have links in the footer that did not appear in the header, and vice versa.

This means that the 'Home' and 'Login' are now in the footer, but not the header. However, the footer menu appears in two columns as shown in the image, which is slightly different than the provided mock. Will discuss with the team to decide on importance of the three column styling.
![screen shot 2016-03-10 at 12 29 09 pm](https://cloud.githubusercontent.com/assets/5429661/13683478/be192286-e6bb-11e5-9956-0eb320d435b1.png)

**Comment by MagdiRizkallah** [comment]
In fact issue #832 is to \style' the footer according to Mock

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM.
