### ISSUE TITLE
Amani-Zen: Missing "Reset" and "Apply" buttons on the Filter section on About > Team

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1017]
Dev site
![team_filter](https://cloud.githubusercontent.com/assets/15751109/11545589/f3b372c8-98fc-11e5-8161-a4f8bdf0582b.png)
Mock on Invision
![team_filter_correct](https://cloud.githubusercontent.com/assets/15751109/11545593/f69182a0-98fc-11e5-87b2-b1ce2c8c7029.png)

**Comment by sheilaj** [comment]
Buttons added. Needs theming.

**Comment by PeaceGeeks** [comment]
ready for theming upon code pull

**Comment by limage** [comment]
Done! Need some update the dev site from Amani-Zen-theme branch later

**Comment by limage** [comment]
Apply!  Need QA.

**Comment by akochlan** [comment]
Validated on dev env. Button added but placed in wrong order and text should be capitalized. Also needs to change color. Failed.

**Comment by akochlan** [comment]
Re-tested. only left is wrong order. Other issues are fixed.

**Comment by limage** [comment]
done with switch APLLY and RESET button

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
