### ISSUE TITLE
Amani-Zen: Incorrect layout for Team Member Introduction 

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1018]
Dev Site
![team_introduction](https://cloud.githubusercontent.com/assets/15751109/11545857/8870fe3e-98fe-11e5-8ecb-aad5e29ffe6a.png)
Mock on Invision
![team_introduction_correct](https://cloud.githubusercontent.com/assets/15751109/11545860/8dbf4580-98fe-11e5-8e83-19cb0aa9c2a5.png)

**Comment by dannyzoujx** [comment]
This is for both Desktop and Mobile.

**Comment by PeaceGeeks** [comment]
@zerhide - is this ticket correct?

**Comment by isingh** [comment]
Verified on dev. Closing.
