### ISSUE TITLE
Amani-Zen: "Read More" button layout on Homepage

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1019]
Dev site
![readmore_homepage_dev](https://cloud.githubusercontent.com/assets/15751109/11546211/b49b4bfc-9900-11e5-9064-9f295989309b.png)
Invision
![readmore_homepage_mock](https://cloud.githubusercontent.com/assets/15751109/11546219/ba36f3b8-9900-11e5-8b00-0930114f488f.png)

**Comment by dannyzoujx** [comment]
Hey hwa

**Comment by limage** [comment]
I have tweaked it before, should be same.

**Comment by akochlan** [comment]
Validated on dev env. READ MORE buttons look the same as on Invision. Passed.

**Comment by PeaceGeeksProjects** [comment]
Verified
