### ISSUE TITLE
Amani-Zen: About > Team, incorrect section heading format

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1020]
Dev site
![sectionheading_dev](https://cloud.githubusercontent.com/assets/15751109/11546699/acfaedfa-9903-11e5-8af0-a97f68fb4711.png)
Invision
![sectionheading_invision](https://cloud.githubusercontent.com/assets/15751109/11546703/b0d5b5ea-9903-11e5-957d-1b5bbc5d7130.png)

**Comment by PeaceGeeks** [comment]
Seems to be correct now on dev so closing.
