### ISSUE TITLE
Amani-Zen: Team node, incorrect layout

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1022]
Dev site
![team_node_dev](https://cloud.githubusercontent.com/assets/15751109/11547256/76e0d12c-9907-11e5-8704-96eb3545adc7.png)
Invision
![team_node_invision](https://cloud.githubusercontent.com/assets/15751109/11547420/7c6202a0-9908-11e5-8af7-4ab08f47e720.png)

Heading should just say "Team". Information layout should follow Invision's design.

**Comment by PeaceGeeks** [comment]
@HwaHueySoh - Can you check with Laura on this one?

**Comment by dannyzoujx** [comment]
Just a note that this is for both Desktop and Mobile version

**Comment by PeaceGeeks** [comment]
The bolded header should read 'Team'. The body is fine as is. There should be another dividing line at the bottom, which includes the 'Back to Team' link as seen on the mock in Invision.

**Comment by limage** [comment]
@MagdiRizkallah Please assign to back end for changing of "The bolded header should read 'Team'. The body is fine as is. There should be another dividing line at the bottom, which includes the 'Back to Team' link as seen on the mock in Invision.", thanks!

**Comment by PeaceGeeksProjects** [comment]
@bensinjin Please help!

**Comment by jayappnovation** [comment]
BAck end Done, "Back to team" button created and changed page title as "Team"

**Comment by jayappnovation** [comment]
Code merged with this PR 
https://github.com/PeaceGeeksSociety/amani/pull/1099

**Comment by jayappnovation** [comment]
Ajusting the styles have to be done

**Comment by erica-scott** [comment]
Completed styles.

**Comment by dannyzoujx** [comment]
Missing a dividing line at the bottom where it should separate the text and the "Back toTeam page" link

**Comment by PeaceGeeksProjects** [comment]
I do not see the line on either mobile or desktop.
https://projects.invisionapp.com/share/TR4QUJ3UY#/screens/107296636

**Comment by erica-scott** [comment]
Added line on bottom.

**Comment by PeaceGeeksProjects** [comment]
Now the lead image overlaps the text.
![zen1022](https://cloud.githubusercontent.com/assets/16202351/14263940/5e6283f8-fa72-11e5-9876-0e76c7a1ceab.JPG)

**Comment by limage** [comment]
Done! https://github.com/PeaceGeeksSociety/amani/pull/1186
@bensinjin Please update dev site from Amani-Zen-Theme branch.thanks!

**Comment by bensinjin** [comment]
Pulled on amani zen

**Comment by MagdiRizkallah** [comment]
Verified on Dev
