### ISSUE TITLE
Amani-Zen: About > Gallery, Incorrect page title

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1023]
"Galleries" should be "Gallery" instead
![gallerytitle](https://cloud.githubusercontent.com/assets/15751109/11548647/81c2e90c-9913-11e5-85c2-f489c47ff2f3.png)

**Comment by sheilaj** [comment]
'Galleries' is a taxonomy term created by the media_gallery module, so I renamed it an update hook in the amani_media_gallery module. Run database update to see the change.

**Comment by HwaHueySoh** [comment]
doesnt look changed. @PeaceGeeks who should i tag to do a fetch from github again?

**Comment by akochlan** [comment]
Validated on dev http://dev.amani-zen-theme.peacegeeks.org/gallery

Still shows GALLERIES. Failed.

**Comment by akochlan** [comment]
Re-tested dev 
![gallery](https://cloud.githubusercontent.com/assets/16566072/12176818/412ea512-b537-11e5-9c4f-3df2eef67ca1.png)
after updates has been done. Looks as expected. Passed.
