### ISSUE TITLE
Amani-Zen: Gallery albums missing dates 

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1024]
Under each album title, there should be a date of when the album is added.
Dev site:
![albumdate_dev](https://cloud.githubusercontent.com/assets/15751109/11548759/9294cb0a-9914-11e5-96cd-2daf0f413f1e.png)
Invision:
![albumdate_invision](https://cloud.githubusercontent.com/assets/15751109/11548761/97391026-9914-11e5-86c9-9f5b13705d41.png)

**Comment by dannyzoujx** [comment]
Just a note that this is happening for both Desktop and Mobile versions. But by fixing one should probably fix the other as well

**Comment by sheilaj** [comment]
I've added the date.

**Comment by HwaHueySoh** [comment]
Ready for themeing

**Comment by limage** [comment]
Done!

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
