### ISSUE TITLE
Amani-Zen: Programs sidebar has a different design

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1025]
Dev site: http://dev.amani-zen-theme.peacegeeks.org/programs
![programsidebar_dev](https://cloud.githubusercontent.com/assets/15751109/11570707/8249f088-99ad-11e5-81e8-67b75d69974f.png)
Invision:
![programsidebar_invision](https://cloud.githubusercontent.com/assets/15751109/11570789/f743fc76-99ad-11e5-8b0f-96b17778fa11.png)

**Comment by limage** [comment]
As per our discussion we decide to keep similar style of side bar like program node page, please confirm this with Renee.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
