### ISSUE TITLE
Amani-Zen: Missing "READ MORE" button on Get Involved page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1026]
Dev site: http://dev.amani-zen-theme.peacegeeks.org/get-involved
![getinvolved_dev](https://cloud.githubusercontent.com/assets/15751109/11574097/74d642e2-99be-11e5-9f2d-f70f07f368d2.png)
Invision:
![getinvolved_invision](https://cloud.githubusercontent.com/assets/15751109/11574108/804d2ec4-99be-11e5-996d-54129a896a96.png)

**Comment by limage** [comment]
Add button already!

**Comment by akochlan** [comment]
Verified on dev http://dev.amani-zen-theme.peacegeeks.org/get-involved. Passed.

**Comment by PeaceGeeksProjects** [comment]
verified
