### ISSUE TITLE
Amani-Zen: Missing action button on Get Involved node pages

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1027]
Make a suggestion, Report an issue, Volunteer, Donate should all have an action button(ex: Submit, Report, Apply, Donate) on their node page. 

Invision:
![getinvolved_node_invision](https://cloud.githubusercontent.com/assets/15751109/11574847/df3e5d46-99c2-11e5-95c0-89fb00e4f3bd.png)

**Comment by dannyzoujx** [comment]
Just a note that this is for both Desktop and Mobile version of the site.

**Comment by PeaceGeeks** [comment]
This looks funny to me. Button should be centered under the text not under the full width of the page.

**Comment by limage** [comment]
I can't export feature from my local, I just manually configure "donation-region" context on dev site.

**Comment by jayappnovation** [comment]
To which url this button have to be linked?

**Comment by PeaceGeeksProjects** [comment]
@jayappnovation There should be a different 'configurable' button on each node.  That should be part of the content type for the get-involved node.

**Comment by akochlan** [comment]
VALIADTED ON DEV: http://dev.amani-zen-theme.peacegeeks.org/ WITH WEB BROWSER: SAFARI, CHROME, FF, IE-10 AND mobile devices ( IOS, Android, Windows).

Steps to reproduce:

1. Login to http://dev.amani-zen-theme.peacegeeks.org/
2. Navigate to Get Involved page node
3. Click on Read More>> under MAKE A SUGGESTION, REPORT AN ISSUE, VOLUNTEER WITH CEPO, DONATE TO CEPO

Works as expected. Passed.

**Comment by PeaceGeeks** [comment]
To clarify @PeaceGeeksProjects comment above, the button should have a configurable label and link

**Comment by bensinjin** [comment]
@PeaceGeeksProjects I've added a configureable link to the content type - you should see it appear as a purple button underneath the body for example see: http://dev.amani-zen-theme.peacegeeks.org/get-involved/make-suggestion (I've just added a random title/link). To configure edit the link field of the node in question.

**Comment by akochlan** [comment]
Validated on desktop and mobile. Button is configurable and centered. Looks good to me. Passed.

**Comment by PeaceGeeksProjects** [comment]
Verified
