### ISSUE TITLE
Amani-Zen: Activities node missing "Back" button

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1029]
Dev site: http://dev.amani-zen-theme.peacegeeks.org/activity/liberia
![activity_dev](https://cloud.githubusercontent.com/assets/15751109/11576555/57cb8dd4-99cc-11e5-9e2d-42a38b6cc813.png)
Invision:
![activity_invisino](https://cloud.githubusercontent.com/assets/15751109/11576558/5cbf622a-99cc-11e5-9170-b3a93f88908c.png)

**Comment by sheilaj** [comment]
Fixed in last commit.

**Comment by sheilaj** [comment]
Forgot to update feature to hide field_program label. Done now.
