### ISSUE TITLE
Amani-Zen: Remove RSS feed button on the Gallery page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1031]
RSS feed button is not needed on the Gallery page (http://dev.amani-zen-theme.peacegeeks.org/gallery)

Dev site: 
![rss_dev](https://cloud.githubusercontent.com/assets/15751109/11576685/62660a66-99cd-11e5-8ce3-2e3c2b6e1406.png)

**Comment by limage** [comment]
Done

**Comment by akochlan** [comment]
Validated on dev env. RSS feed button is removed. Passed.

**Comment by PeaceGeeksProjects** [comment]
Verified
