### ISSUE TITLE
Amani-Zen: Incorrect filter widget on Resources page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1032]
Dev site: http://dev.amani-zen-theme.peacegeeks.org/resources
![filter_resources_dev](https://cloud.githubusercontent.com/assets/15751109/11576806/37a8d744-99ce-11e5-965f-18c6751fdd0d.png)

Invision:
![filter_resources_invision](https://cloud.githubusercontent.com/assets/15751109/11576808/3d0da2aa-99ce-11e5-81ba-f0bb588f2230.png)

Check Frontify (https://app.frontify.com/d/kGdWxDMw21JF/amani-zen-style-guide#/feed-event-widgets) for more info if needed

**Comment by dannyzoujx** [comment]
Just adding a note as this is for both Desktop and Mobile version of the site

**Comment by jayappnovation** [comment]
On Amani-zen-theme branch, Added the "Keyword" filter

**Comment by limage** [comment]
themieng for change order and add "Keyword"

**Comment by akochlan** [comment]
Validated on dev http://dev.amani-zen-theme.peacegeeks.org/resources:

1. missed label FILTERS on the top.
2. DATE SELECT  section looks different than on mockup.
3.  Wrong order RESET and SUPLY buttons

**Comment by limage** [comment]
fixed #1 and #3 https://github.com/PeaceGeeksSociety/amani/pull/1084
@MagdiRizkallah #2 The DATE SELECT widget is hard to change, please bring up this issue to Renee.
Code in Amani-Zen-Theme branch, wait for push to dev.

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks Can you decide on the DATE SELECT widget?

**Comment by PeaceGeeksProjects** [comment]
I think the current widget is acceptable and easier for the end user.  I am closing this despite the different mock-up for the Date widget.
