### ISSUE TITLE
Amani-Zen: Missing "Add Record" button on Resources > Map

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1033]
Invision:
![addrecord_map](https://cloud.githubusercontent.com/assets/15751109/11577036/b89b8dc8-99cf-11e5-876c-6a95edb63f19.png)

**Comment by dannyzoujx** [comment]
Just adding a note as this is for both Desktop and Mobile version of the site

**Comment by PeaceGeeks** [comment]
@bensinjin @MagdiRizkallah where is this button. I know we already have one in core

**Comment by PeaceGeeks** [comment]
Button is there but needs to be themed and should be on by default

**Comment by limage** [comment]
Done with button styling!

**Comment by akochlan** [comment]
Validated on dev http://dev.amani-zen-theme.peacegeeks.org/mapping-conflict-violence-in-south-sudan. Button ADD RECORD is shown up but need  colour theming.

**Comment by akochlan** [comment]
On Mobile: ADD RECORDS button is overlapping and not visible. New defect will be opened.

**Comment by PeaceGeeksProjects** [comment]
This is due to #1053 hiding the Map will also hide the button.
