### ISSUE TITLE
Amani-Zen: Incorrect format for individual incidents on Resources > Map

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1034]
Each item below the map does not have a brief synopsis,  time and location is also formatted differently in mock site vs invision

Dev site:
![incident_dev](https://cloud.githubusercontent.com/assets/15751109/11577281/9a52584a-99d1-11e5-8f9d-587f84b35cb3.png)

Invision:
![incident_invision](https://cloud.githubusercontent.com/assets/15751109/11577284/9ed6164a-99d1-11e5-898a-0b839f2353c4.png)

**Comment by dannyzoujx** [comment]
Just adding a note as this is for both Desktop and Mobile version of the site

**Comment by PeaceGeeks** [comment]
@bensinjin - have they created a different view for this page to core? I don't see any issue with adding this to core if it is not already there.

**Comment by bensinjin** [comment]
@PeaceGeeksProjects This looks to be done to me, let me know if this is not the case? I'm moving this to done please let me know if this is not the case.

**Comment by akochlan** [comment]
Validated on desktop and mobile. Looks good now. Passed.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & iphone
