### ISSUE TITLE
Amani-Zen: Incorrect content layout on News node page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1035]
Title and subtitle are differently formatted. Date of published is at the bottom instead of under the subtitle.

Dev site:
![news_node_dev](https://cloud.githubusercontent.com/assets/15751109/11577897/ebe1a220-99d5-11e5-8af1-531d211b84bf.png)

Invision:
![news_node_invision](https://cloud.githubusercontent.com/assets/15751109/11577908/f13ef8c6-99d5-11e5-968f-9d489ac8051a.png)

**Comment by PeaceGeeks** [comment]
@HwaHueySoh - can you check with Laura on this one?

**Comment by PeaceGeeks** [comment]
The image should not be displaying twice on the node (seems to be specific to this node only?) 

Style according to mock including missing sidebar

**Comment by PeaceGeeks** [comment]
Double image image is fixed (same image was uploaded as the Main and Media image)

**Comment by limage** [comment]
@MagdiRizkallah Please assign this ticket to back end for changing of "Title and subtitle are differently formatted. Date of published is at the bottom instead of under the subtitle.", thanks!

**Comment by PeaceGeeksProjects** [comment]
@limage how about the side bar showing other News above Recent Comments.

**Comment by limage** [comment]
@PeaceGeeksProjects According to the mock, the side bar showing other News and Recent Comments also need to be enabled.

**Comment by PeaceGeeksProjects** [comment]
@bensinjin Please Help!

**Comment by bensinjin** [comment]
Ok I've deployed the necessary work to dev. The sidebar still needs styling though - all the necessary content is there now though. @limage see http://dev.amani-zen-theme.peacegeeks.org/news/south-sudan-expels-un-humanitarian-coordinator for example. (Needs a bit of styling love).

**Comment by bensinjin** [comment]
Err I'm not clear if we need a new image style for the image or not? I don't see it mentioned here? If so feel free to create/featurize one.

**Comment by PeaceGeeksProjects** [comment]
@bensinjin I think the date is missing under the title

**Comment by bensinjin** [comment]
Huh? I see it..
![screen shot 2016-02-04 at 5 31 36 pm](https://cloud.githubusercontent.com/assets/3228323/12835464/2f706ab0-cb65-11e5-848a-bf6c7a3217f7.png)

**Comment by bensinjin** [comment]
This is from http://dev.amani-zen-theme.peacegeeks.org/news/vancouver-under-wildfire-smoke

**Comment by PeaceGeeksProjects** [comment]
My mistake... I need glasses!

**Comment by limage** [comment]
https://github.com/PeaceGeeksSociety/amani/pull/1088
@bensinjin Done with the styling! Please update the dev site. We may want to create new image style for the image, please consult to Renee as well, thanks!

Have a good longweek end!

**Comment by dannyzoujx** [comment]
Verified on dev http://dev.amani-zen-theme.peacegeeks.org/news/vancouver-under-wildfire-smoke

**Comment by MagdiRizkallah** [comment]
@PeaceGeeks @isingh The side bar is showing 'Programs' not 'other News'...  Moving back to ToDo
