### ISSUE TITLE
Amani-Zen: Missing sidebar on News node page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1036]
News node page on Dev currently does not have a sidebar at all.

Invision: https://projects.invisionapp.com/share/KB4R6KBD9#/screens/116352528
![news_node_sidebar](https://cloud.githubusercontent.com/assets/15751109/11578032/b2b571ec-99d6-11e5-8762-553cf0518bb6.png)

**Comment by sheilaj** [comment]
Added sidebar views and context. Needs theming.

**Comment by isingh** [comment]
This is verified on dev. Closing.
