### ISSUE TITLE
Amani-Zen: Incorrect layout for Contact page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1037]
Order of the fields are different between Dev and Invision (name-email-subject on dev,  subject-name-email on invision)
Send message button on the left side on dev, right side on invision

Dev site: http://dev.amani-zen-theme.peacegeeks.org/contact
![contact_dev](https://cloud.githubusercontent.com/assets/15751109/11578220/3a2722be-99d8-11e5-9d50-daed69d1881a.png)

Invision: https://projects.invisionapp.com/share/KB4R6KBD9#/screens/107297113
![contacts_invision](https://cloud.githubusercontent.com/assets/15751109/11578223/458fefbe-99d8-11e5-8a2a-149035b9240f.png)

**Comment by PeaceGeeks** [comment]
Dev site is correct. Closing
