### ISSUE TITLE
Amani-Zen: Sidebar on Programs node page is missing "MORE" button

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1040]
Dev site: http://dev.amani-zen-theme.peacegeeks.org/content/capacity-building-csos-state-institutions
![programs_node_more_dev](https://cloud.githubusercontent.com/assets/15751109/11597671/e8db460c-9a71-11e5-9152-047b3694586d.png)

Invision:
![programs_node_more_invision](https://cloud.githubusercontent.com/assets/15751109/11597673/ecd15ed6-9a71-11e5-8ac8-3b318425506a.png)

**Comment by limage** [comment]
Already there!
http://dev.amani-zen-theme.peacegeeks.org/content/capacity-building-csos-state-institutions

**Comment by akochlan** [comment]
Verified on dev. MORE link is there on Programs node page.

@MagdiRizkallah Q: is it supposed to be link or button? Mockup shows button.

**Comment by PeaceGeeksProjects** [comment]
Verified
