### ISSUE TITLE
Amani-Zen(mobile): Missing "Donate" button on the homepage

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1045]
There should be a "Donate" button beside "What we do"

Dev site: http://dev.amani-zen-theme.peacegeeks.org/
![donate_dev](https://cloud.githubusercontent.com/assets/15751109/11672751/175ada02-9dc8-11e5-8dd6-a5a6740fee6e.png)

Invision: https://projects.invisionapp.com/share/KB4R6KBD9#/screens/107296432
![donate_invision](https://cloud.githubusercontent.com/assets/15751109/11672755/21687144-9dc8-11e5-840f-60cd5da0cfa1.png)

**Comment by limage** [comment]
same as #1027, manually configure on dev site.

**Comment by PeaceGeeksProjects** [comment]
@limage This is NOT same as #1027. It is already configured on Dev site and appears on the Web.  It needs to also show on Mobile.  Moving it back to In Progress

**Comment by limage** [comment]
fixed! https://github.com/PeaceGeeksSociety/amani/pull/1083
code in Amani-Zen-Theme branch, need push to dev.

**Comment by PeaceGeeksProjects** [comment]
@bensinjin Dev & Lybia Please ...

**Comment by PeaceGeeksProjects** [comment]
Verified on iPhone
