### ISSUE TITLE
Amani-Zen(mobile): Filter not appearing as a dropdown on Team page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1046]
Dev site: http://dev.amani-zen-theme.peacegeeks.org/team
![filter_dev](https://cloud.githubusercontent.com/assets/15751109/11672919/67a82fae-9dc9-11e5-99ad-495221d43383.png)

Invision: https://projects.invisionapp.com/share/KB4R6KBD9#/screens/110963119
![filter_invision](https://cloud.githubusercontent.com/assets/15751109/11672924/771c21e8-9dc9-11e5-9085-b435af9567b5.png)

**Comment by PeaceGeeks** [comment]
Low priority - same treatment should be applied to 'Resource' filter styles if and when we do this one.

**Comment by arvandtiv** [comment]
please view changes http://dev.amani-zen-theme.peacegeeks.org/team

**Comment by akochlan** [comment]
Validated on dev: http://dev.amani-zen-theme.peacegeeks.org/team. Looks as expected. Passed.

**Comment by PeaceGeeksProjects** [comment]
Also verified on iPhone
