### ISSUE TITLE
Amani-Zen(mobile): Missing "Back to team" button on Team node page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1047]
Invision site: https://projects.invisionapp.com/share/KB4R6KBD9#/screens/110963215

![backtoteam_invision](https://cloud.githubusercontent.com/assets/15751109/11673495/294c5104-9dce-11e5-9ec3-00de6b900ace.png)

**Comment by dannyzoujx** [comment]
Just a note that this is for both Desktop and Mobile site, but solving one would solve the other

**Comment by jayappnovation** [comment]
Related to this ticket
https://github.com/PeaceGeeksSociety/amani/issues/1022

**Comment by PeaceGeeksProjects** [comment]
Duplicate closing
