### ISSUE TITLE
Amani-Zen: Gallery node page header has incorrect format

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1048]
Header of the page is formatted differently: Top should say “gallery”, with gallery title left aligned below and the date added to the right of that.

Dev site: http://dev.amani-zen-theme.peacegeeks.org/galleries/16-days-activism
![gallerynode_title_dev](https://cloud.githubusercontent.com/assets/15751109/11695924/a9083208-9e66-11e5-8fbf-d6fe9181a7b8.png)

Invision: https://projects.invisionapp.com/share/KB4R6KBD9#/screens/107296651
![gallerynode_title_invision](https://cloud.githubusercontent.com/assets/15751109/11695930/b2c70184-9e66-11e5-8236-0a266306613a.png)

This is also the case on the mobile version of the site. End result on the mobile site should look like this: https://projects.invisionapp.com/share/KB4R6KBD9#/screens/111870468
![gallerynode_title_mobile](https://cloud.githubusercontent.com/assets/15751109/11696005/06cd8884-9e67-11e5-8588-96fa49d422f1.png)

**Comment by limage** [comment]
@MagdiRizkallah Please assign this ticket to back end people, thanks!

**Comment by bensinjin** [comment]
@PeaceGeeksProjects  I've done some work on this - I fail to see the need for two versions of the title (in this ex. 16 Days of Activision) - anyways give me your feedback from dev.

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks I agree with @bensinjin .  Although now it meets the design, I think the design may have overlooked the fact that this is the only Node that has 2 titles rather than simply the Node Title at the top...

**Comment by akochlan** [comment]
Validated on http://dev.amani-zen-theme.peacegeeks.org/galleries/16-days-activism. To be precise. Expected: "16 Days of Activism" should be displayed twice on desktop: above the line and under the line. Actual: Only above the line. 2. On mobile it should displayed under the line according to mockup. Failed.

@PeaceGeeksProjects  Please, correct me if I am wrong.

**Comment by PeaceGeeksProjects** [comment]
You are right, but they both look good enough for me....  Closing
