### ISSUE TITLE
Amani-Zen: Pager for gallery node page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1049]
Currently on the dev environment there isn't an album with enough photos to show the pager. Would like to have one for the purpose of testing.

**Comment by PeaceGeeks** [comment]
@MagdiRizkallah - can you add some photos to this please?

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks How many photos / page is needed?

**Comment by PeaceGeeks** [comment]
4 rows of images?

**Comment by PeaceGeeks** [comment]
@MagdiRizkallah - did you add photos? It looks like that request came from me, but I don't recall writing it so I'm a bit confused

**Comment by PeaceGeeks** [comment]
Oh i see this was in reference to Li's comment above. Looks like you did this. I'm also fine with a long page like this. If we want to add a pager at a later date, we can do that after. I am closing this for now.
