### ISSUE TITLE
Amani-Zen(mobile): Filter should appear as a expandable button on Resources

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1050]
Filters and filter options should be a button to expand, instead of a mandatory expanded version shown in dev site

Dev site: 
![filter_resources_dev](https://cloud.githubusercontent.com/assets/15751109/11698426/542354ae-9e73-11e5-8e9b-5e1d27d263f4.png)

Invision: https://projects.invisionapp.com/share/KB4R6KBD9#/screens/116627724
![filter_resources_invision](https://cloud.githubusercontent.com/assets/15751109/11698430/5c5298a6-9e73-11e5-9095-2400a6f9089d.png)

**Comment by limage** [comment]
Done! https://github.com/PeaceGeeksSociety/amani/pull/1070

**Comment by PeaceGeeksProjects** [comment]
Verified on iPhone
