### ISSUE TITLE
Amani-Zen: Missing document details on the Resources page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1051]
For the articles on the Resources page, they are all missing some info such as type, theme and location.

Dev site: http://dev.amani-zen-theme.peacegeeks.org/resources
![resources_details_dev](https://cloud.githubusercontent.com/assets/15751109/11698688/e0f2bc34-9e74-11e5-8e4f-bc0f9ddefac4.png)

Invision: https://projects.invisionapp.com/share/KB4R6KBD9#/screens/107296938
![resources_details_invision](https://cloud.githubusercontent.com/assets/15751109/11698695/e8ae623e-9e74-11e5-8b7d-7f03d85dbbac.png)

**Comment by dannyzoujx** [comment]
Just adding a note as this is for both Desktop and Mobile version of the site

**Comment by bensinjin** [comment]
These fields are not missing they are just not populated on dev - they require taxonomy terms & values.

**Comment by bensinjin** [comment]
For example I've added some of the values in on the first resource here: http://dev.amani-zen-theme.peacegeeks.org/resources

**Comment by akochlan** [comment]
Validated on desktop and mobile by successfully added values on third resource. Passed.

**Comment by PeaceGeeksProjects** [comment]
Verified
