### ISSUE TITLE
Amani-Zen: Missing "DOWNLOAD" button under each article on the Resources page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1052]
Dev site does not have download icon at bottom of each resource box. 

Invision: https://projects.invisionapp.com/share/KB4R6KBD9#/screens/107296938
![resources_download_invision](https://cloud.githubusercontent.com/assets/15751109/11698764/4af644de-9e75-11e5-89b1-036250ba6632.png)

**Comment by dannyzoujx** [comment]
Just adding a note as this is for both Desktop and Mobile version of the site
![resources_download_mobile](https://cloud.githubusercontent.com/assets/15751109/11698794/742e3f50-9e75-11e5-8cee-f96034dfde85.png)

**Comment by limage** [comment]
https://github.com/PeaceGeeksSociety/amani/pull/1078
Export feature for Resource page, please make a feature revert.

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks  There seems to be a visual conflict between the 'Download' button that is shown on the mockup of resources  above and the 'Link' field of the resource if it is used http://dev.libya.peacegeeks.org/?q=resources

How do we resolve this?

**Comment by PeaceGeeksProjects** [comment]
@limage Here is what we agreed on:
Download link should only appear when there is 'Media' attached on the Resource (This is working)
The 'Link' added to a resource should NOT have the download icon added.

Please remove the download icon from the 'Link' line and keep it only for 'Download' if any.

**Comment by limage** [comment]
fixed! https://github.com/PeaceGeeksSociety/amani/pull/1082
code in Amani-Zen-Theme branch, wait for dev site updated

**Comment by PeaceGeeksProjects** [comment]
@bensinjin Could you please move to Dev & Lybia...

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
