### ISSUE TITLE
Amani-Zen(mobile): Lastest Incidents on the Map page should be two per row

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1054]
Lastest Incidents on the Map page should be two per row instead of one.

Dev site: http://dev.amani-zen-theme.peacegeeks.org/mapping-conflict-violence-in-south-sudan
![incidents_dev](https://cloud.githubusercontent.com/assets/15751109/11699196/02fd99f4-9e78-11e5-893d-2e5a80ea0873.png)

Invision:
![incidents_invision](https://cloud.githubusercontent.com/assets/15751109/11699201/072ea630-9e78-11e5-9963-067f24df7d17.png)

**Comment by PeaceGeeks** [comment]
This is a discrepancy, but we like the dev site as -with one column for readability - is so closing.
