### ISSUE TITLE
Amani-Zen: Incorrect style for the "MORE" button on the Map page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1055]
Please follow the READ MORE button design on Frontify (https://app.frontify.com/d/kGdWxDMw21JF/amani-zen-style-guide#/basics/buttons)

Dev site: http://dev.amani-zen-theme.peacegeeks.org/mapping-conflict-violence-in-south-sudan
![map_more_dev](https://cloud.githubusercontent.com/assets/15751109/11699314/af00328e-9e78-11e5-98eb-64f3a9d3bbd4.png)

**Comment by dannyzoujx** [comment]
Just adding a note as this is for both Desktop and Mobile version of the site

**Comment by limage** [comment]
Done, also set list 6 items for the page.

**Comment by jayappnovation** [comment]
![screen shot 2016-01-05 at 2 35 13 pm](https://cloud.githubusercontent.com/assets/10199352/12125514/95ed8624-b3b9-11e5-858b-a37e227f5720.png)

**Comment by jayappnovation** [comment]
That is the current styling...Is that oki? @PeaceGeeks

**Comment by akochlan** [comment]
Validated on dev http://dev.amani-zen-theme.peacegeeks.org/mapping-conflict-violence-in-south-sudan , web desktop and mobile. Looks as expected, see screenshot.
![more button](https://cloud.githubusercontent.com/assets/16566072/12176616/3d51bffc-b536-11e5-860c-e001c6390ece.png)

**Comment by PeaceGeeksProjects** [comment]
According to the style guide it should be 
<img width="158" alt="amanuzenreadmore" src="https://cloud.githubusercontent.com/assets/16202351/12177206/cfbbf586-b51f-11e5-85a8-841a96471200.png">

**Comment by jayappnovation** [comment]
Issue Fixed and Merged on the Amani-zen-theme branch

Related to this PR:  https://github.com/PeaceGeeksSociety/amani/pull/1104

**Comment by dannyzoujx** [comment]
Verified on dev http://dev.amani-zen-theme.peacegeeks.org/mapping-conflict-violence-in-south-sudan

**Comment by MagdiRizkallah** [comment]
Confirmed
