### ISSUE TITLE
Front Page Box Links not working

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeksSociety/amani#1068]
you get this error when you click on any FPB
The requested page "/%5Bfield_link%5D" could not be found.

Try it at http://dev.amani-zen-theme.peacegeeks.org/

**Comment by bensinjin** [comment]
@MagdiRizkallah @PeaceGeeksProjects See http://dev.amani-zen-theme.peacegeeks.org/ - should be fixed now.

**Comment by PeaceGeeksProjects** [comment]
The 'Read More' link works.  However, when you click on the image you get the same error as in #829

**Comment by erica-scott** [comment]
This was fixed just by a simple re-arranging of fields in the view. A pull request was created and merged in Amani-Zen-Theme. The code will need to be pushed to the dev site and the feature reverted.

**Comment by PeaceGeeksProjects** [comment]
Verifi8ed on Dev
