### ISSUE TITLE
Header and Footer not centred on Android mobile

### ISSUE THREAD

**Issue by akochlan** [PeaceGeeksSociety/amani#1069]
Testing env: Samsung Galaxy S4, Motorola Moto G, iPhone 4 ( real devices not emulator).

Steps to reproduce:

1. Navigate to PeaceGeeks home page on dev http://dev.amani-zen-theme.peacegeeks.org/.

Actual: Header and Footer not centred on Android mobile, see screenshot.

NOTE: Header and Footer on iPhone looks good. 

![header android mobile](https://cloud.githubusercontent.com/assets/16566072/12200688/501c3898-b5ee-11e5-9d3b-a429ef0776c9.png)
![footer android mobile](https://cloud.githubusercontent.com/assets/16566072/12200695/59462cd0-b5ee-11e5-907f-05bc57f1fd11.png)

**Comment by akochlan** [comment]
Updated screenshots

![header_android_mobile](https://cloud.githubusercontent.com/assets/16566072/12203687/4c7663b6-b5fe-11e5-9200-f4b7211dcdd3.jpg)


![footer_android_mobile](https://cloud.githubusercontent.com/assets/16566072/12203693/529416b2-b5fe-11e5-8158-c541af3e3e07.jpg)

**Comment by limage** [comment]
fixed! https://github.com/PeaceGeeksSociety/amani/pull/1085
Code in Amani-Zen-Theme branch!

**Comment by PeaceGeeksProjects** [comment]
@bensinjin Dev & Lybia Please ...

**Comment by bensinjin** [comment]
Lybia deployed.

**Comment by akochlan** [comment]
Re-tested on env: Samsung Galaxy S4. Looks good. Passed.

**Comment by PeaceGeeksProjects** [comment]
Tx Alex...
