### ISSUE TITLE
Amani-Zen: "Add Record" button is overlapped on Mobile phones and not visible on  Resources > Map

### ISSUE THREAD

**Issue by akochlan** [PeaceGeeksSociety/amani#1075]
Testing eng: iPhone 4 ( iOS 9/ Safari )and Samsung Galaxy S4 ( Android 5/Chrome ).

1. Navigate to http://dev.amani-zen-theme.peacegeeks.org/mapping-conflict-violence-in-south-sudan

Actual: "Add Record" button is overlapped  and not visible on RESOURCES->MAP page, see screenshot.
![iphone landscape](https://cloud.githubusercontent.com/assets/16566072/12396271/779c5d6a-bdd4-11e5-9d23-7a2a0b7763bb.png)
![iphone portrait](https://cloud.githubusercontent.com/assets/16566072/12396274/7aec8b5c-bdd4-11e5-93dc-94ad4a513ca1.png)

**Comment by PeaceGeeksProjects** [comment]
This is due to #1053 hiding the Map will also hide the button.
