### ISSUE TITLE
Amani-Zen: Map and "Add Record" button is not shown up on iPad's Resources > Map

### ISSUE THREAD

**Issue by akochlan** [PeaceGeeksSociety/amani#1076]
Testing env: iPad 7.1.2

1. Navigates to http://dev.amani-zen-theme.peacegeeks.org/mapping-conflict-violence-in-south-sudan

ACTUAL: No Map is displayed, no ADD RECORDS button, see screenshot.
![img_0013](https://cloud.githubusercontent.com/assets/16566072/12396899/ebc0633c-bdd7-11e5-80f8-e853b1637208.jpg)

**Comment by PeaceGeeksProjects** [comment]
This is probably due to #1053
