### ISSUE TITLE
Partners Carousel not showing

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1079]
enabled on Dev but not showing

**Comment by PeaceGeeksProjects** [comment]
@erica-scott Still not showing... moving back to In Progress

**Comment by PeaceGeeksProjects** [comment]
@erica-scott now it shows all the time even when disabled.

**Comment by erica-scott** [comment]
Made changes to the Amani Admin configuration for enabling/disabling the partners carousel.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
