### ISSUE TITLE
Remove Download option from embedded videos

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1089]
Or make it Admin select-able.  It gives an error on YouTube embedded nodes
http://dev.amani-zen-theme.peacegeeks.org/resources
 
![zen1089-1](https://cloud.githubusercontent.com/assets/16202351/12925423/0ed052fa-cf13-11e5-9a44-536b8f7193c9.JPG) 
![zen1089-2](https://cloud.githubusercontent.com/assets/16202351/12925504/6bb4519c-cf13-11e5-990b-9d100403d0e3.JPG)

**Comment by erica-scott** [comment]
Created merge request https://github.com/PeaceGeeksSociety/amani/pull/1098

**Comment by dannyzoujx** [comment]
verified on dev. Download option is removed.

**Comment by MagdiRizkallah** [comment]
Confirmed...  However, caused anther issue #1112
