### ISSUE TITLE
Expose changes to home page blocks to non superadmin user

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1091]
This is related to #789 
We want to allow the access to configuration of the block to non superadmin users

**Comment by PeaceGeeks** [comment]
So this would be a config option for an Amani Admin user? That is really just restating #789 because if we allowed that, it would have to be configurable by Amani Admins. 

@mackh - what was your concern with this? I know you raised an issue a while ago.

**Comment by mackh** [comment]
concern is that the the security plan is to limit non super admin used from having "administer blocks" permissions

but hey, if you trust them, thats fine :) could lead to breakage if there is a training gap

**Comment by PeaceGeeksProjects** [comment]
@mack - what does this give them access to?




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype.* reneeontheroad

**Comment by PeaceGeeksProjects** [comment]
Anyway to limit their ability to manage that specific block in that specific view?

**Comment by isingh** [comment]
+1 for what Magdi said. We want the ablity to add/configure front page blocks but thats about it. This can be done manually for clients (and potentially wont change very often) but it would be nice to have.

**Comment by PeaceGeeksProjects** [comment]
I don't think it works that way - I think its either all views or no views.
They wouldn't necessarily be provided with links to other views, but they
could theoretically get there. At least that is my understanding.




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype.* reneeontheroad

**Comment by PeaceGeeksProjects** [comment]
Moving to Backlog until we decide the best way to deal with that.  PeaceGeeks can help the partners until we decide what to give Amani Admins...

**Comment by pg-amani-pub** [comment]
Great - please make sure that Appno folks are clear that they are not to
address issues in the backlog at this time. Thanks Magdi!




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype.* reneeontheroad

**Comment by isingh** [comment]
This is done now
