### ISSUE TITLE
Sub Menus do not appear when hovering over the menu item on LYM

### ISSUE THREAD

**Issue by aavram** [PeaceGeeksSociety/amani#1094]
They behave properly in the Zen Dev site (appear as you hover over th emenu item)
http://dev.amani-zen-theme.peacegeeks.org/

But they only appear when you actually click the menu item on LYM:
http://dev.lym.peacegeeks.org

**Comment by isingh** [comment]
This bug also exists on amani website. If you are not on "News & Events" Tab, it wont show blog as a hover menu. But if you are it starts showing up.

**Comment by erica-scott** [comment]
This has been resolved on LYM, related to pull request https://github.com/PeaceGeeksSociety/amani/pull/1095. The same fix could be completed on dev as well. It's just based on the checkbox "Show as Expanded" that is an option on each menu link.

**Comment by PeaceGeeksProjects** [comment]
Verified on both sites
