### ISSUE TITLE
Ability to disable comments for the website

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1100]
We want an amani admin configuration that allows us to disable comments from the entire website. This means no one will see the UI to add comments, or comments (if any) will not be displayed either.

**Comment by erica-scott** [comment]
This capability was added to the Amani Admin configuration settings.

**Comment by erica-scott** [comment]
After looking at some other things, I realize my implementation of this was not consistent with the rest of the Amani Admin functions so I fixed that to work the same way.

**Comment by dannyzoujx** [comment]
verified on dev.
Comments can be enabled/disabled at /admin/configure-amani, under Manage site-wide comments

**Comment by MagdiRizkallah** [comment]
Confirmed
