### ISSUE TITLE
Cropped Lead images are not fully displayed on the page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1107]
![screenshot 2016-03-10 13 32 45](https://cloud.githubusercontent.com/assets/15751109/13685607/1586f070-e6c6-11e5-9d54-25d39df01e82.png)
There is an issue with cropped images  not fully displayed on the page. The attached screenshot is based on this news article (http://dev.amani-zen-theme.peacegeeks.org/news/vancouver-under-wildfire-smoke)

Steps to reproduce:
- create an article page
- upload a lead image to the article
- crop the image
- Save and go to the page to verify if the image is displayed properly

**Comment by erica-scott** [comment]
Noticed the conflicts for this merge request were a result of some changes I made last week. Resolved those and merged.

**Comment by dannyzoujx** [comment]
It seems like their is a visual bug on the cropping rectangle box. It is showing the whole image within the image itself (see attached screenshot)
Steps:
- edit an article
- upload an image
- try to resize the rectangle box

Notice the rectangle box is showing the full image itself and just re-sizing it when we shrink/expand it.
![screenshot 2016-03-24 16 34 04](https://cloud.githubusercontent.com/assets/15751109/14034265/da249ef0-f1de-11e5-87e8-e23dfff17fa8.png)

**Comment by dannyzoujx** [comment]
Here is another screenshot
![screenshot 2016-03-24 16 39 02](https://cloud.githubusercontent.com/assets/15751109/14034318/69316f06-f1df-11e5-97b1-f25645c34e8b.png)

**Comment by limage** [comment]
fixed! https://github.com/PeaceGeeksSociety/amani/pull/1158
@bensinjin @mackh Please update it!

**Comment by MagdiRizkallah** [comment]
Now the lead image does not show... see #1121

**Comment by isingh** [comment]
Is there a work around for this? This affects images uploaded to front page boxes and slide shows (especially ones not in proportion?). Its a blocker for LYM.

**Comment by PeaceGeeksProjects** [comment]
@isingh  Would a work around be to crop the image before upload?

**Comment by isingh** [comment]
Can we get the exact sizes for which we would not need to crop? I can try it on that size and see if works.

**Comment by PeaceGeeksProjects** [comment]
there is an issue requesting all image sizes (#1140), but no one has responded yet.  I will try to find out by trial and error :(

**Comment by PeaceGeeksProjects** [comment]
I uploaded a 320x240 Image in the centre box on Dev - http://dev.amani-zen-theme.peacegeeks.org/

**Comment by isingh** [comment]
I tried uploading a 1440x450 image on LYM in the slideshow, and its still messed up. I downloaded the image from Amani Zen, and the end result is still the same. 
I tried the following:
![cafod photo library_0_0_0](https://cloud.githubusercontent.com/assets/1025545/14932768/10c920d4-0e31-11e6-8fbf-07ffd1a4ece4.jpg)

![slide1](https://cloud.githubusercontent.com/assets/1025545/14932770/1761a646-0e31-11e6-8707-092b3e6e7385.jpg)

**Comment by isingh** [comment]
I think the cropping broke? I tried editing dev site, and saw that a full sized 4:3 image was uploaded. Trying to crop the image differently gave different results on the dev site, and now that slideshow image is broken

**Comment by PeaceGeeksProjects** [comment]
Agreed - Magdi, let's have someone look at this next week.

@Mack - can we get some of Ben's time this coming week? I feel like there
is clean-up needed that requires his attention.




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype**.* reneeontheroad
*pgp. *9253 3C6E 70B4 5211 6854 ED5E B585 C32D 264C 9CB6

**Comment by isingh** [comment]
We currently cant add any slideshow slides, and fixing this would unblock us. Right now for other images, we can upload images which are proportioned right. But in case of slideshows that doesnt help either.

**Comment by PeaceGeeksProjects** [comment]
@isingh I am separating the Slide show issue into #1187.

**Comment by bensinjin** [comment]
I've deployed a fix for https://github.com/PeaceGeeksSociety/amani/issues/1187 I think this may have resolved this issue too. Please confirm.

**Comment by MagdiRizkallah** [comment]
Verified on Dev & LYM
