### ISSUE TITLE
Calendar Page Views not showing content

### ISSUE THREAD

**Issue by erica-scott** [PeaceGeeksSociety/amani#1111]
If you go to any of these links (for any date):
http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/2015-11-19
http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/week/2015-11-19
http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/day/2015-11-19

there is no data being shown in the calendar, and the header is not displaying the date either. Clearly an issue with the view or the way it's being displayed.

**Comment by erica-scott** [comment]
This was fixed based on some css issues, and also added some custom code to fix the calendar titles.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
