### ISSUE TITLE
Remove Link button on the embedded videos node page

### ISSUE THREAD

**Issue by dannyzoujx** [PeaceGeeksSociety/amani#1112]
The link button is blocking the embedded youtube video. It needs to be moved away from the video.
Need confirmation as where the button should go.

![screenshot 2016-03-11 13 52 18](https://cloud.githubusercontent.com/assets/15751109/13716737/d991fe9e-e791-11e5-9020-c9a5865a73d6.png)

**Comment by MagdiRizkallah** [comment]
This is probably a side effect from the resolution of #1089...  There are now link buttons showing incorrectly and not linking to the right place. e.g. in http://dev.amani-zen-theme.peacegeeks.org/resource/support
click on the pdf icon you get the proper download pop-up.  Click on the button 'Support Link' and you get to the news & events page???
![image](https://cloud.githubusercontent.com/assets/5035201/13724572/9bbaf712-e83e-11e5-897c-c9a754f969c8.png)

**Comment by erica-scott** [comment]
After discussion with Magdi and Renee, decided that the bottom section should have the name of the PDF file (which is clickable and links to the document) and then have a button that says 'DOWNLOAD' that links to the same pdf file. Then, the external link for the resource (if it has one) should appear in the section where the date is, as a link. This is in accordance with the mock.

However, for the situation where the media is a youtube video and not a pdf file, we do not want to show the 'DOWNLOAD' button as the video is shown as an embedded video, and not a link.

These changes have been completed, and just needs to be pushed to the dev site.

**Comment by PeaceGeeksProjects** [comment]
Tx @erica-scott works well now!  Verified on Dev
