### ISSUE TITLE
No icons for Instagram and Youtube

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1119]
Icons for Instagram and YouTube dont show up in the footer or in the header.

<img width="102" alt="screen shot 2016-03-18 at 11 52 10 am" src="https://cloud.githubusercontent.com/assets/1025545/13888683/e3b8df3c-ecff-11e5-9ff4-e147c2a6ea9a.png">
![zen1119](https://cloud.githubusercontent.com/assets/16202351/13890981/a8675fb0-ed0b-11e5-9e36-568df6103f0e.JPG)

**Comment by erica-scott** [comment]
The Instagram icon existed in the amani-font code, and just needed to be added to the CSS. The only two icons missing from the different social media items, are YouTube and Pinterest. Once the icons are added to the font, the icon 'number' will need to be added to the sass/css.

The footer changes are in _footer.scss on line 218 and 227.
The header changes are in _menus.scss on line 108 and 120.
Just need to add the font code into the content section.

**Comment by erica-scott** [comment]
I was able to use the added ss-social (assuming this is the old font) to add in the Youtube and Pinterest icons that were missing from the font, however, their style is slightly different. I've added an image that shows the difference, it's not hugely noticable, but if it's a problem we will need to track down the proper icons and add them to the font.
![screen shot 2016-04-01 at 1 32 16 pm](https://cloud.githubusercontent.com/assets/5429661/14219284/5224b428-f80e-11e5-8509-f3930b7e0570.png)

**Comment by PeaceGeeksProjects** [comment]
Instagram icon looks wrong on the site.

![zen1119](https://cloud.githubusercontent.com/assets/16202351/14264249/da0b8602-fa73-11e5-972e-ef3f56c42235.JPG)

**Comment by isingh** [comment]
Should we add a separate tickets for Youtube and Pinterest icons? Those icons look very different from the rest.

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks This needs a designer to create the icons in the same 'style' as the rest.

@isingh  I don't think it needs separate tickets, but if you think of any more icons, we should add them here.

**Comment by limage** [comment]
@bensinjin Please update again https://github.com/PeaceGeeksSociety/amani/pull/1175 thanks!

**Comment by limage** [comment]
Add same style of youtube and pinterest to Amani icons set

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
