### ISSUE TITLE
News node sidebar theming issues

### ISSUE THREAD

**Issue by erica-scott** [PeaceGeeksSociety/amani#1121]
The news node sidebar displays three articles, but right now, the CSS has some issues if there is no image attached to the article so some CSS changes will need to be added for the situation where there is no image.

This is the way it looks without images:
![screen shot 2016-03-18 at 12 51 41 pm](https://cloud.githubusercontent.com/assets/5429661/13890356/3689b9e0-ed08-11e5-80d8-1bb808f7c82d.png)
This is what it looks like with images:
![screen shot 2016-03-18 at 12 51 48 pm](https://cloud.githubusercontent.com/assets/5429661/13890358/37afccb0-ed08-11e5-8324-89eebba4e520.png)

**Comment by limage** [comment]
fixed!  https://github.com/PeaceGeeksSociety/amani/pull/1157

**Comment by MagdiRizkallah** [comment]
Tx @limage However, now  the lead image does not show...
![image](https://cloud.githubusercontent.com/assets/5035201/14401259/e2d797e0-fdbf-11e5-9422-3ace3fb750da.png)
moving back to in progress.

**Comment by limage** [comment]
@bensinjin I have export feature for lead image style,  please update it in dev5, thanks!
https://github.com/PeaceGeeksSociety/amani/pull/1169

**Comment by appnoviv** [comment]
Fix verified.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
