### ISSUE TITLE
Social Media icons conflict with the Search button in the header

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1123]
on LYM http://dev.lym.peacegeeks.org/
They look fine on Dev???

![zen1119](https://cloud.githubusercontent.com/assets/16202351/13891028/eea54bc2-ed0b-11e5-92d7-928f03926926.JPG)

**Comment by erica-scott** [comment]
This was resolved by CSS, but we are still missing the YouTube icon, which will need to be added. That will be resolved by https://github.com/PeaceGeeksSociety/amani/issues/1119 which is similar and the issue will be attended to.

**Comment by dannyzoujx** [comment]
Is it possible to evenly space out the icons and the search box, right now it seems to be unevenly spaced.
![screenshot 2016-03-24 15 12 56](https://cloud.githubusercontent.com/assets/15751109/14032871/06399b78-f1d3-11e5-9c4e-a096a1345749.png)

**Comment by PeaceGeeksProjects** [comment]
and for some reason overlapping on LYM http://dev.lym.peacegeeks.org/

moving back to in progress

**Comment by erica-scott** [comment]
The reason this was happening only on LYM is because it was having different results depending on how many social media items there are. I've fixed the CSS so it is uniform, regardless of how many items you are displaying.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM

**Comment by PeaceGeeksProjects** [comment]
@limage This reappeared after loading new icons...

**Comment by limage** [comment]
There is new menu item"Home" add to navigation bar, also social icons could list up to 9 items, so I did some optimized work for responsive themeing. The icons and menu item overlay issue has been solved.
@bensinjin Please update Amani-Zen-theme branch to Dev site https://github.com/PeaceGeeksSociety/amani/pull/1181, thanks!

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
