### ISSUE TITLE
Dropdown menu doesnt appear for Programs

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1127]
The drop down menu for "Programs" doesnt appear, unless you in under programs.

For example if you go to `http://dev.lym.peacegeeks.org/?q=resources`, the drop down menu for `Programs` doesnt appear. However once you click on `Programs`, you can see the drop down menu options.

**Comment by PeaceGeeksProjects** [comment]
you need to click on 'expanded' checkbox\
![zen1127](https://cloud.githubusercontent.com/assets/16202351/13940481/fa471bcc-ef9a-11e5-95cc-a178107cbb39.JPG)

Closing...
