### ISSUE TITLE
Logo is not updating using the 'Configure Amani' Manage Logo and Tagline page

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#1131]
http://dev.amani-zen-theme.peacegeeks.org/admin/configure-amani/site-info

**Comment by erica-scott** [comment]
The theme in which the logo was being uploaded to was hardcoded to be the 'peace' theme, I changed it so it is now dynamic, and sends the theme name for the theme that is current enabled.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
