### ISSUE TITLE
Change default weight value to ensure order of Main Menu

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1135]
Home -50
    About -50 => -40
    Programs -49 => -35
    Get Involved -48 => -30
    Resources -47 => -25
    News & Events -46 => -20
    Contact -43 => 0

**Comment by erica-scott** [comment]
Exported the menu links to maintain the order of the menu.

**Comment by MagdiRizkallah** [comment]
@bensinjin is this what keeps resetting the menu after each upgrade?

Moving back to in progress.

**Comment by bensinjin** [comment]
The menu links should not be in features, I will be removing them. I can probably tweak the rebuild menu function to set weights.

**Comment by PeaceGeeksProjects** [comment]
@bensinjin That would be GREAT!!!

**Comment by bensinjin** [comment]
Ok they've been removed from features and I've deployed to amani-zen, lym and libya. I'm going to have to spend a bit of time refactoring that rebuild function to allow for weights and possible parent elements? Anyways I'll probably bug you at some point magdi to gather further reqs. around it.

**Comment by PeaceGeeksProjects** [comment]
Tx @bensinjin !  Bug me anytime :)

**Comment by bensinjin** [comment]
Ok this has been deployed.
