### ISSUE TITLE
Map on edit Map record is broken

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1138]
http://dev.amani-zen-theme.peacegeeks.org/node/397/edit
![zen1138](https://cloud.githubusercontent.com/assets/16202351/14035244/324a0a20-f1e9-11e5-9bf5-4bd28523f6e4.JPG)

**Comment by bensinjin** [comment]
We're using the admin theme for editing/creating content - this fixes this issue. Moving to done.

**Comment by brandonq-appnovation** [comment]
If I select a point on the map and save the Map Report, should this point display as the Geolocation on the Map Report node page? Currently, it is not doing that.

**Comment by bensinjin** [comment]
@bradnovation this has been resolved.

**Comment by brandonq-appnovation** [comment]
There is one issue left regarding this ticket.

When a user is creating or editing a Map Record node and clicks "Find Address on Map", duplicate buttons for the map drawing tools appear over the map. These duplicates should not appear.

![pgks_map_duplicate_buttons](https://cloud.githubusercontent.com/assets/19274675/15228862/19812cf0-1843-11e6-8802-4495271a8269.png)

Everything else looks to be correct though. The map displays and functions correctly on the node create/edit page, and placing a location on the map gives the correct Geolocation on the node page.

**Comment by bensinjin** [comment]
@brandonq-appnovation we may have to live with this for now. It's a known bug with the module and really we need to find a good chunk of time to possibly remove it as it has other quirks we've encountered. This should probably be moved to the backlog.

**Comment by brandonq-appnovation** [comment]
As per @bensinjin 's comment, moving this to the backlog.

**Comment by isingh** [comment]
Closing this issue. I have filed #1207 to track the outstanding UI issue.
