### ISSUE TITLE
Document best sizes for images in different spots.

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1140]
Logo
Slideshow
Front Page Box
Partner  Logo
Lead Image (in each content type)
Media options
other?

**Comment by bensinjin** [comment]
@PeaceGeeksProjects maybe @limage should weigh in on this as I'm not as familiar where various fields appear throughout the site. I do think though if there is a strict requirement on an image to be a certain size there should be field validation to enforce this - it shouldn't have to be documented.

**Comment by PeaceGeeksProjects** [comment]
@limage what do you think...  may be as you discover them put the 'recommended' sizes in the help text of each field.

**Comment by limage** [comment]
Yes, I will write down the 'recommended' sizes of this list.

**Comment by limage** [comment]
Here is 'recommended' sizes of following list:
1. Logo: any width x 120px height;
2. Slideshow image: Drupal will crop image to 1440 X 450px;  any size image bigger than 1440 X 450px will be work, but I recommend image size smaller than 4M for uploading.
3. Front page box: Drupal will corp image to 200x150px height;
4. Lead Image (in each content type): Drupal should crop image to 676 X 500px; 
5. List view images include sidebar images (in each content type): Drupal should crop image to 480 X 355px; 

The program page need to be applied new image style, current images looks blurry.

**Comment by PeaceGeeksProjects** [comment]
Tx @limage ... I added these to the Amani Documentation.  Closing this issue.
