### ISSUE TITLE
Add ability to change the header text of blocks on the home page

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1141]
We want to be able to change the header of blocks on home page.
For example 'Latest events' could be called 'Latest Opportunities and Events'

<img width="443" alt="screen shot 2016-03-31 at 6 58 50 pm" src="https://cloud.githubusercontent.com/assets/1025545/14195817/be9438b4-f772-11e5-8db5-8c85b5c7c940.png">

**Comment by erica-scott** [comment]
In the same place where you can decide to enable/disable the home page feed blocks, added a title field, and by clicking the enable button, it will change the title to whatever you've entered there.

**Comment by PeaceGeeksProjects** [comment]
Title works fine.  Ordering does not keep the changed value after saving.
@bensinjin @mackh @isingh
is this due to it still being configured in the features?
Is it easy to remove it from the standard installation configuration?
