### ISSUE TITLE
Add ability to reorder the blocks that show on the Home Page

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1142]
For example we may want the social media feeds to appear last, or we want the Latest blog to appear before latest articles etc.

**Comment by erica-scott** [comment]
Added a config section under the MANAGE FRONT PAGE FEED TYPES section that allows the config to update the weights of the feeds, and therefore, re-ordering them.

**Comment by bensinjin** [comment]
Erica I'm afraid your changes for this will be lost if you revert the amani global feature .. which is something we need to be able to do. We simply cannot support every feature request (realistically) and there are some rules (like not allowing feature overrides) that we sort of need to abide by.

**Comment by PeaceGeeksProjects** [comment]
Ordering does not keep the changed value after saving.
@bensinjin @mackh @isingh
is this due to it still being configured in the features?
Is it easy to remove it from the standard installation configuration?

**Comment by bensinjin** [comment]
@PeaceGeeksProjects this is a setting that will occasionally get reverted on deploys and will just have to be reset. Sorry there isn't a great solution to functionality like this without spending a significant amount of time. I'm moving to closed and we can come up with a different solution if we find this issue to be an on going problem.

**Comment by MagdiRizkallah** [comment]
Tx @bensinjin Moving to backlog to consider in future releases...

**Comment by isingh** [comment]
This is done. Closing.
