### ISSUE TITLE
Remove the frame/shadow from images shown in articles/blogs

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1144]
<img width="249" alt="screen shot 2016-03-31 at 7 04 53 pm" src="https://cloud.githubusercontent.com/assets/1025545/14195876/7c5146bc-f773-11e5-91fe-13e4b4c43b38.png">

**Comment by erica-scott** [comment]
Removed the css that was making this occur.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
