### ISSUE TITLE
Display the Author for Blogs/Articles

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1145]
Client would like to be able to indicate the author of an article, but authors may not be users on the site.  

Proposed solution is to have a new Taxonomy for Authors, which has an Author Name and behaves like a tag.  On the blog and article listing pages, the stories should be able to be filtered by the Author list

**Comment by bensinjin** [comment]
goto admin/structure/taxonomy/author/add to add terms for this taxo, the field has been added to blogs and articles. Can you specify what you mean by 'the stories should be filter by the Author list' ? Where are the stories?

**Comment by PeaceGeeksProjects** [comment]
@bensinjin I guess we need to update the Dev & LYM sites for this to appear.  Did you create 2 Taxonomies Blog Author & Article Author?  a Story would be either a blog or an article.  They would be automatically filtered in a 'taxonomy view' by clicking on the author.  The author field should also be part of the 'list' view (landing page of 'News & Events' or 'Blog' - also in the front page blocks)

**Comment by bensinjin** [comment]
I have added these fields, the taxonomies need to be populated, this has
been deployed to dev.amani-zen-theme, dev.lym and dev.libia.

On Mon, Apr 4, 2016 at 6:10 PM, PeaceGeeksProjects <notifications@github.com

**Comment by PeaceGeeksProjects** [comment]
@bensinjin I still can see only one taxonomy (Author).  We would need 'Blog Author' and 'Article Author'.

**Comment by bensinjin** [comment]
I thought you guys needed an author on blog & and author on article? This is what I've done. They can draw from the same taxonomy can they not?

**Comment by bensinjin** [comment]
This taxonomy view - that's a new view correct? We don't currently have a view showing blocks & articles do we? Where (what would the path be) of this view?

**Comment by PeaceGeeksProjects** [comment]
I think we need two separate taxonomies @bensinjin the authors for Blogs are totally different from the Articles authors

I don't know about any new taxonomy view, I use the standard Drupal taxonomy view (Manage Picklists in the Amani Admin Menu)

**Comment by bensinjin** [comment]
I'll be working on this today.

**Comment by bensinjin** [comment]
We now have an Article Author & and Blog Author field pointing to different taxonomies on their respective content types. This has been deployed to dev.lym, dev.amani-zen and dev.lybia

Managing the taxonomies works as you'd expect. I haven't done anything with view as of yet as I'm not clear exactly what the requirements for this should be?

**Comment by PeaceGeeksProjects** [comment]
Tx @bensinjin the view needs are on #1160 moving this to Done

**Comment by MagdiRizkallah** [comment]
Verified on Dev.
