### ISSUE TITLE
LYM Clean URLs not working

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/amani#1154]
http://dev.lym.peacegeeks.org/?q=admin/config/search/clean-urls

Shows error
Clean URLs cannot be enabled. If you are directed to this page or to a Page not found (404) error after testing for clean URLs

**Comment by bensinjin** [comment]
clean urls enabled at: http://dev.lym.peacegeeks.org/admin/config/search/clean-urls

**Comment by bensinjin** [comment]
@PeaceGeeksProjects this has been fixed.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
