### ISSUE TITLE
Remove duplicate item in Amani config menu

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1155]
![zen1155](https://cloud.githubusercontent.com/assets/16202351/14265442/5d0a5194-fa76-11e5-97a6-f68092c93fb9.JPG)

**Comment by brandonq-appnovation** [comment]
Tested and verified on Amani Zen Theme dev site.

The duplicate "Manage front page feed" has been removed from the "Configure Amani" page.

![pgks_remove_duplicate](https://cloud.githubusercontent.com/assets/19274675/15202922/8f8c0b12-17b3-11e6-9fa6-25ffcf2cd40e.png)

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
