### ISSUE TITLE
Show Author in Blog/Article Feed on node view and landing pages

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1160]
We need to have the blog/article author name be visible along with the date in the feed.

Currently it only shows date in case of Blog, and nothing in case of articles.

<img width="721" alt="screen shot 2016-04-06 at 6 36 38 pm" src="https://cloud.githubusercontent.com/assets/1025545/14337848/884e26bc-fc26-11e5-9016-56cb92b3cef3.png">

**Comment by PeaceGeeksProjects** [comment]
Also place the fields under the title in the node view (same font as in the landing page view above)
Date, Author, and Blog Category or Article Type
e.g. 
![zen1160](https://cloud.githubusercontent.com/assets/16202351/14348537/ffb0c7dc-fc71-11e5-931e-be5cb620eec3.JPG)

**Comment by bensinjin** [comment]
Please see #1192. This has been deployed.

**Comment by PeaceGeeksProjects** [comment]
Superceded by #1192

**Comment by isingh** [comment]
I would like to keep this open. #1192 is a bigger task, and it will be great to have this one first. If 1192 is being actively worked on we should close this, otherwise lets keep it open?

**Comment by PeaceGeeksProjects** [comment]
@isingh This is done already... all what is remaining is the styling which is 1192.

**Comment by isingh** [comment]
Ok, I added an author, and it works as expected. Thanks!

**Comment by pg-amani-pub** [comment]
Please move to Done then




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype**.* reneeontheroad
*pgp. *9253 3C6E 70B4 5211 6854 ED5E B585 C32D 264C 9CB6

**Comment by isingh** [comment]
Its already Closed? Do you want to move it back to Done?

**Comment by PeaceGeeksProjects** [comment]
DO NOT move back to done please.  Renee is unaware of details...
