### ISSUE TITLE
Display Author, Date, Category inside a Blog/Article

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1161]
Currently for Blog we show author and category at bottom and dont show date. We want to show all three at the top below the heading.

<img width="1037" alt="screen shot 2016-04-06 at 6 38 30 pm" src="https://cloud.githubusercontent.com/assets/1025545/14337867/dcf394fe-fc26-11e5-8753-43aa584d5378.png">

In case of articles it shows time, but it doesnt show any other information.

<img width="730" alt="screen shot 2016-04-06 at 6 38 18 pm" src="https://cloud.githubusercontent.com/assets/1025545/14337874/eade7822-fc26-11e5-939c-9326dbb51d5b.png">

**Comment by jayappnovation** [comment]
Done pushed on Amani zen theme branch

**Comment by PeaceGeeksProjects** [comment]
Tx @jayappnovation did you see #1160 as well?

**Comment by jayappnovation** [comment]
No I didn't!

Will fix and push it later today :)

Thanx

On Fri, Apr 15, 2016 at 3:32 PM, PeaceGeeksProjects <
notifications@github.com> wrote:

> Tx @jayappnovation <https://github.com/jayappnovation> did you see #1160
> <https://github.com/PeaceGeeksSociety/amani/issues/1160> as well?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/PeaceGeeksSociety/amani/issues/1161#issuecomment-210608533>
>



-- 
<http://email.appno.net/email-top.php>

Jerome Tchania
Drupal Developer

5455 de Gaspé Avenue, Suite 370
Montréal, QC, H2T 3B3 Canada
www.appnovation.com


<CASLunsubscribe@appnovation.com?subject=Unsubscribe&body=I%27m+sorry+to+hear+that+you+wish+to+unsubscribe,+just+send+this+message+and+we%27ll+remove+you.>
<http://email.appno.net/email-bottom.php>

**Comment by bensinjin** [comment]
Please see https://github.com/PeaceGeeksSociety/amani/issues/1192. This has been deployed.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM

**Comment by isingh** [comment]
Was this fixed on LYM? I dont see author names in articles.

**Comment by PeaceGeeksProjects** [comment]
@isingh The fields need to be filled to appear...

**Comment by PeaceGeeks** [comment]
magdi, do you mean that taxonomy values need to be added?




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype**.* reneeontheroad
*pgp. *9253 3C6E 70B4 5211 6854 ED5E B585 C32D 264C 9CB6


On Fri, May 6, 2016 at 9:18 AM, PeaceGeeksProjects <notifications@github.com
