### ISSUE TITLE
Header and Footer menu gets reset after each deploy

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1162]
All the menu items get reset, whenever LYM gets deployed too

**Comment by PeaceGeeksProjects** [comment]
@bensinjin May be related to #1135

**Comment by limage** [comment]
@bensinjin The LYM site is missing logos on footer, I have exported feature(including 2 logo beans) of footer, please update it. https://github.com/PeaceGeeksSociety/amani/pull/1185

**Comment by bensinjin** [comment]
This is what we've decided on:
-Main menu should be duplicated in footer (that way when we update main the footer also reflects this)
-Main menu links are generated via the 'Reset menu' button in configure amani
-Existing footer menu links should be removed from features and replaced with three links: Login/Logout, and Admin (see https://github.com/PeaceGeeksSociety/amani/issues/1188)
-Footer menu will display beside main menu in the footer.

**Comment by bensinjin** [comment]
This has been deployed.

**Comment by PeaceGeeksProjects** [comment]
Verified on LYM
