### ISSUE TITLE
Home page social feeds background image shows below the block

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1163]
The image below is supposed to be the background image of the Social Feed Block

<img width="1103" alt="screen shot 2016-04-08 at 3 31 02 pm" src="https://cloud.githubusercontent.com/assets/1025545/14399184/0bd9b8a6-fd9f-11e5-977c-aaafd0a447e6.png">

**Comment by MagdiRizkallah** [comment]
See comment on #1147
Closing as duplicate.
