### ISSUE TITLE
From Amani Config menu, replace link for Logo & 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#1166]
Go to http://dev.amani-zen-theme.peacegeeks.org/admin/configure-amani (Configure Amani)
Select 'Manage Logo and Tagline' button
Replace link for button with link to admin/configure-amani/site-info 

Or else reconfigure the existing link so that the user can actually manage the logo and tagline

**Comment by MagdiRizkallah** [comment]
@peacegeeks i think the existing link config/system/site-information is needed too.  It seems that the division you requested in #798 & #799 has not happenned and need to be implemented fully.

**Comment by MagdiRizkallah** [comment]
Duplicate of  #798 & #799... Closing
