### ISSUE TITLE
Homepage does not appear to be themed for mobile

### ISSUE THREAD

**Issue by appnoviv** [PeaceGeeksSociety/amani#1171]
- Open the site on a mobile device (I used a Samsung Galaxy S5)
- Homepage does not appear to be themed properly to display on the mobile device
![screenshot_2016-04-21-12-03-37](https://cloud.githubusercontent.com/assets/18451461/14721123/981e4e0c-07b9-11e6-8cc0-1cffe253cdc2.png)

**Comment by limage** [comment]
@bensinjin Please update dev site https://github.com/PeaceGeeksSociety/amani/pull/1179, thanks!

**Comment by PeaceGeeksProjects** [comment]
Verified Dev on iPhone
