### ISSUE TITLE
Margins are not properly set on a tablet

### ISSUE THREAD

**Issue by appnoviv** [PeaceGeeksSociety/amani#1172]
- Go to the homepage on a tablet
- Scroll to the right and eventually user will see large whitespace and just the donate button
- The social media icons are not available in the menu bar
- Search button is overlapping the Home menu link
![img_0998](https://cloud.githubusercontent.com/assets/18451461/14726904/c61dec10-07da-11e6-8fa1-2a315c461ec4.PNG)

Expected results:
- Margin should be properly set on the tablet so that the page displays properly

**Comment by limage** [comment]
@bensinjin  Please update dev site https://github.com/PeaceGeeksSociety/amani/pull/1173, thanks!

**Comment by PeaceGeeksProjects** [comment]
Verified Dev on iPhone
