### ISSUE TITLE
Several elements overlap on the homepage on Mobile

### ISSUE THREAD

**Issue by appnoviv** [PeaceGeeksSociety/amani#1176]
- Go to the homepage on a Mobile device (I used an Iphone5)
- Several elements on the page overlap
- See screenshots for details

![img_0697](https://cloud.githubusercontent.com/assets/18451461/14756276/e8e5ccd2-089c-11e6-8dbd-7a518319f28c.PNG)

![img_0698](https://cloud.githubusercontent.com/assets/18451461/14756281/edb6291e-089c-11e6-944d-cc71a886c655.PNG)

**Comment by MagdiRizkallah** [comment]
Verified on android & iphone
