### ISSUE TITLE
Social media icons are not aligned properly on Mobile

### ISSUE THREAD

**Issue by appnoviv** [PeaceGeeksSociety/amani#1178]
- Go to the homepage on a Mobile device
- Scroll to the footer at bottom of the page
- The social media are not aligned properly

![img_0700](https://cloud.githubusercontent.com/assets/18451461/14756436/1f518f12-089e-11e6-8ba5-1855b537bd7b.PNG)

**Comment by limage** [comment]
@bensinjin Please update the PR to Dev site, https://github.com/PeaceGeeksSociety/amani/pull/1180
thanks!

**Comment by PeaceGeeksProjects** [comment]
Verified Dev on iPhone
