### ISSUE TITLE
No spacing between slideshow and front page boxes

### ISSUE THREAD

**Issue by isingh** [PeaceGeeksSociety/amani#1183]
The slideshow doesnt have any padding below it, and front page boxes meld into it.

<img width="1050" alt="screen shot 2016-04-29 at 12 58 00 pm" src="https://cloud.githubusercontent.com/assets/1025545/14928002/2080dc46-0e0a-11e6-8038-30aeebca6ca2.png">

**Comment by PeaceGeeksProjects** [comment]
Work around here is to leave white spacing on top of all pics

**Comment by isingh** [comment]
Ok, lets see if we can fix this to begin with, else I am going to Photoshop resized images.

**Comment by isingh** [comment]
Also if we have to enter small images (because of the cropping bug) putting whitespace on top will make them very tiny.

**Comment by PeaceGeeksProjects** [comment]
320x240 worked.  see #1107 fro details

**Comment by PeaceGeeksProjects** [comment]
Results of my trials at http://dev.amani-zen-theme.peacegeeks.org/
Left image 800x600
Centre image 320x240
Right image 1600x1200 with 25 pixels white at the top

So it seems any size image proportioned 4x3 would work with some white space on top.

**Comment by limage** [comment]
Put 20px between slidshow and front page boxes https://github.com/PeaceGeeksSociety/amani/pull/1184
@bensinjin Please update dev site from Amani-Zen-Theme, thanks!

**Comment by PeaceGeeksProjects** [comment]
@limage No effect on Dev.  Can you check please?

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
