### ISSUE TITLE
Slideshow image cropping does not work

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1187]
Tried to upload several pics at different ratios 1*1, 1*2, 1*3, 1*4 with 2048 pix wide to no avail.

**Comment by isingh** [comment]
Thanks for separating this, as this is a blocker for LYM.

**Comment by limage** [comment]
@PeaceGeeksProjects I have re-upload the image(slide call "Test")  in Firefox browser, It looks fine.

**Comment by PeaceGeeksProjects** [comment]
@limage What are the original sizes of the pic?  And see the crop box behavior below...
![zen1187](https://cloud.githubusercontent.com/assets/16202351/15030825/6ae71e8c-1209-11e6-9776-1691bfd4aa14.JPG)

**Comment by limage** [comment]
@PeaceGeeksProjects  The original size is 2048x1152px, I just did it again for uploading, nothing wrong

**Comment by limage** [comment]
![screen shot 2016-05-04 at 3 16 04 pm](https://cloud.githubusercontent.com/assets/5281717/15031083/30bedbd0-120b-11e6-9e1f-16a765015193.png)

**Comment by PeaceGeeksProjects** [comment]
I think we need Ben on this. @Mackh - can you advise if we will get Ben's
time this week?




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype**.* reneeontheroad
*pgp. *9253 3C6E 70B4 5211 6854 ED5E B585 C32D 264C 9CB6

**Comment by PeaceGeeksProjects** [comment]
Just to clarify, were you both using the same photo to do the same task?




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype**.* reneeontheroad
*pgp. *9253 3C6E 70B4 5211 6854 ED5E B585 C32D 264C 9CB6

**Comment by limage** [comment]
This is current image in dev site http://dev.amani-zen-theme.peacegeeks.org/sites/default/files/slideshow-field_image/beautiful-matterhorn-background-image-hd-new-wallpapers-for-background_0_0_0.jpg

**Comment by PeaceGeeksProjects** [comment]
I tried it on my firefox and it still gives me the 'inflexible' crop box shown in the above comment...

**Comment by mackh** [comment]
I reviewed permissions briefly, looked ok but I didnt get a chance to test this fully, can you take a look?

**Comment by bensinjin** [comment]
This is theme related. Quickest fix: give amani admins the permission "Use administrative theme". This will only appear when creating and editing content in my opinion it's a nicer theme to use for this anyways. If this is not adequate it might be worth asking @limage if he can see any obvious differences between seven and amani zen theme when creating slideshows.

**Comment by PeaceGeeksProjects** [comment]
I think it is lot less work than to ZENitize all the Admin pages.

**Comment by bensinjin** [comment]
This fix is in, if sufficient pls close.

**Comment by MagdiRizkallah** [comment]
Verified on Dev & LYM
