### ISSUE TITLE
Footer Menu (Admin secondary Menu) needs to be stacked vertically

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1191]
ADMIN should appear below Logout

**Comment by limage** [comment]
https://github.com/PeaceGeeksSociety/amani/pull/1194
@bensinjin Please update dev site from Amani-Zen-theme branch, thanks!

**Comment by MagdiRizkallah** [comment]
Verified on Dev & LYM
