### ISSUE TITLE
Upcoming Events list block styling, Calendar styling.

### ISSUE THREAD

**Issue by bensinjin** [PeaceGeeksSociety/amani#1202]
So we've had the need to tweak the calendar and also show the upcoming events block in new places which has resulted in some styling dropping off. This is what we need:

1) Style the upcoming events block on specific days - the page that shows when you click an event on the calendar. http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/day/2016-05-13 (see right sidebar upcoming events) for example should look as it does at http://dev.amani-zen-theme.peacegeeks.org/news-and-events.

2) Style the upcoming events block on event nodes - http://dev.amani-zen-theme.peacegeeks.org/event/test-event-3-2-days (see right sidebar upcoming events) for example should look as it does at http://dev.amani-zen-theme.peacegeeks.org/news-and-events.

3) Finally, for the calendar we've switch to using the mini version - this is to allow us to hide days from previous months. Some styling has dropped off:
This -
![screen shot 2016-05-13 at 2 54 20 pm](https://cloud.githubusercontent.com/assets/3228323/15262949/9f17ec78-191a-11e6-9b97-34aea444f263.png)

Should look like this - 
![screen shot 2016-05-13 at 12 43 57 pm](https://cloud.githubusercontent.com/assets/3228323/15262956/aed2e10e-191a-11e6-8bfa-e62a562cfcd7.png)

And this -
![screen shot 2016-05-13 at 2 55 30 pm](https://cloud.githubusercontent.com/assets/3228323/15262970/cc326fe4-191a-11e6-90df-4c32eb99c063.png)

Should look like this - 
![screen shot 2016-05-13 at 12 44 15 pm](https://cloud.githubusercontent.com/assets/3228323/15262973/d431e8aa-191a-11e6-9a93-65a9b296962b.png)

Be sure to check all paths these blocks show up on: front page, news-and-events, days (when clicking on calendar events, and finally event nodes. Ensure the image behind the blocks on the front page is also positioned correctly.

**Comment by brandonq-appnovation** [comment]
I have identified two other things that could be added to the daily view (pages like http://dev.amani-zen-theme.peacegeeks.org/calendar-of-events/day/2016-05-16) from my testing of #1159 :

- It would be helpful to have the date as the title of the page.
- There should be some spacing between the events themselves.
![pgks_calendar_day_view_adjustments](https://cloud.githubusercontent.com/assets/19274675/15263873/82abf2de-1922-11e6-86f6-0a672468642b.png)

**Comment by bensinjin** [comment]
The date is now in place.

**Comment by limage** [comment]
Done!
@bensinjin Please update dev site from Amani-Zen-Theme branch, thanks!
https://github.com/PeaceGeeksSociety/amani/pull/1206

**Comment by bensinjin** [comment]
Deployed, moving to done.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
