### ISSUE TITLE
Cannot MANAGE FLOATING BUTTON

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/amani#1203]
![zen1203](https://cloud.githubusercontent.com/assets/16202351/15270216/e64c3ca0-19cb-11e6-8b20-39dac4adb00b.JPG)

**Comment by PeaceGeeksProjects** [comment]
I also tried to add a link to see if another button will show, but nothing happened...

**Comment by bensinjin** [comment]
Resolved and deployed.
