### ISSUE TITLE
Left/right arrow keys do not work in text edit fields (Map record & Events)

### ISSUE THREAD

**Issue by rstorjohann** [PeaceGeeksSociety/amani#140]
Repro steps:

1. Logged in using an Editor (I think!) account, rasmus1, password foobar
2. Clicked My content tab
3. Under Add new content, clicked Add Map Record
Expected: Can use left/right arrow keys to move through the title filed, and Shift-left/right to select text
Observed: left/right arrow keys have no effect
Work around: Navigation and selection still possible with mouse

URL: http://dev.amani.peacegeeks.org/node/add/incident-report
Ubuntu 12.04 / Firefox 22 64-bit
Account: rasmus1 / foobar

**Comment by MagdiRizkallah** [comment]
Fixed on Map Records.  Events fields still not responding to arrow keys except for the description field.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
