### ISSUE TITLE
Map record pop-up bubble does not display image or text teaser

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#335]
bubble should display content beyond node title - ideally image w short teaser text

**Comment by limage** [comment]
fixed including carousel https://github.com/PeaceGeeksSociety/amani/pull/1170
@bensinjin @mackh please update the dev site, thanks!

**Comment by bensinjin** [comment]
dev site updated

**Comment by appnoviv** [comment]
@MagdiRizkallah - The text appears on the bubble but I can't seem to edit the map content without it being removed from the map.  I've tried adding the pin location and save but it doesn't seem to work.  Also how much text would you like displayed in the bubble?  All text is being displayed on the bubble.  I assume teaser meaning that you want may 2 = 3 lines displayed and user would need to click on Read More to read the rest.  Thanks.

**Comment by PeaceGeeksProjects** [comment]
Moving to Backlog

**Comment by isingh** [comment]
Closing, as the bubble shows the text and image. I have added #1208 to call out the changes above.
