### ISSUE TITLE
Document all Default Image sizes and scaling if any

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeksSociety/amani#581]
Different Content Types and fields (Lead Image, Slideshow, Body, Media, Partner Logo,etc. )

**Comment by PeaceGeeks** [comment]
Also  related to #456

**Comment by isingh** [comment]
Is this an exact size, or more of an aspect ration problem? Also this should not matter if cropping tool works.

**Comment by gurinderappno** [comment]
I am not familiar with the concept of documentation. This also seems related to #456 . If it can be explained to me how to proceed with these two tickets I can proceed further.

**Comment by PeaceGeeksProjects** [comment]
Tx @gurinderappno  Just document on the issue as done in #1140 if you can add more info.

#456 was for the Original theme..

**Comment by gurinderappno** [comment]
| Page   |  max-width | max-height |
|----------|:-------------:|------:|
| Partners page |  264px | 164px |
| Programs page |    326px   |   244px |
| News and events | 326px |    244px |
| All events | 326px |    244px |
| Blog | 200px | 148px |
| Team page | 290px | 290px |
