### ISSUE TITLE
'Article' feed on home should be configurable to include other content types

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#789]
Blog
Event
Article 
etc.

**Comment by PeaceGeeks** [comment]
Should be deployed to Amani core.

**Comment by PeaceGeeks** [comment]
Create menu option under 'Configure Amani' for managing configuration

**Comment by PeaceGeeks** [comment]
As discussed with Jerome and Bosco

**Comment by PeaceGeeks** [comment]
Should go into core amani too

**Comment by jayappnovation** [comment]
This has already been built to be configurable.  Any content type can be added to the feed from the admin interface by updating the appropriate views display.  Let me know if you want me to show you how.

**Comment by PeaceGeeks** [comment]
@jayappnovation - can you show me where/ how?

**Comment by akochlan** [comment]
Verified on dev env with superadmin/ p3ac3g33k!. Works as expected. Pass.

**Comment by akochlan** [comment]
Steps to reproduce:

1.  go to structure > views
2.  Look for this view name “news and events” then click on the button “edit”.
3. Make sure that you select the “Block” display.
4. Then go to the “filter criteria” section.
5. click on the second line (Content type)
6. select “content types” that we want to show on the article feed…
7. Then click on the save button

**Comment by PeaceGeeksProjects** [comment]
@akochlan please DO NOT use superadmin (and do not put the PWD on comments or emails anywhere).

As per our Skype, I needed your email address to create you an Alex account.  Please Create yourself an account to test properly as an Amani Admin...

**Comment by akochlan** [comment]
Hello, 

The Amani Admin account has been created: alexk/Test1234

**Comment by akochlan** [comment]
It didn't mention anywhere that should be managed by Amani Admin :)

**Comment by PeaceGeeksProjects** [comment]
NP @akochlan ... We have some restrictions for our Amani Administrators to avoid upgrade issues :)

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks I reopened ths issue since Amani Admins do not have access to the configuration.  There should be some permission changes.

**Comment by isingh** [comment]
@akochlan I tried those steps but can't get the feed to change. Here is the screen capture [PeaceGeeks789-lowres.mov](https://files.zenhub.io/56c393785d3a5c4e4bb3aad0)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by mackh** [comment]
Looks like this is close, probably just needs a little tuning?

**Comment by erica-scott** [comment]
Based on testing this, this seems to be working as specified, by following these steps:
1. Login as an Amani Admin
2. Go to admin/structure/views
3. Look for this view name “news and events” then click on the button “edit”.
4. To change anywhere where the block is set choose Block, to change the front page choose Front Page
5. Then go to the “filter criteria” section.
6. click on the second line (Content type)
7. select “content types” that we want to show on the article feed…
8. Select "This block (override)" on dropdown box.
9. Click on Apply and then Save button

**Comment by PeaceGeeksProjects** [comment]
Tx Erica,  That worked when I chose 'Front Page'.  I had chosen 'Block' before.
What is the difference between them?
http://dev.amani-zen-theme.peacegeeks.org/
Now has Articles & Blogs mixed but sorted by latest...

**Comment by dannyzoujx** [comment]
Verified on dev.
- make sure to click Save after editing and applying the changes

**Comment by MagdiRizkallah** [comment]
Confirmed
