### ISSUE TITLE
Move Contact Page management fields to 'Manage Contact Page Settings'

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#798]
The following fields should be managed under 'Configure Amani' > 'Manage Contact Page Settings'

This should contain fields that are currently found in 'Manage Site Info and Logo' at /admin/configure-amani/site-info - these fields should be removed from this page and included under 'Manage Contact Page Settings' > 'Manage Contact Page' (new button)

Fields:
Address
Lat
Long 
Phone
Email

Please delete the field 'Hours of Operation' from code altogether. 

Also, the link to 'Convert your address' for Lat and Long should open up a new window, ideally a pop-up.

**Comment by bensinjin** [comment]
Done and deployed to dev.amani-zen-theme.peacegeeks.org & dev.libya.peacegeeks.org.

**Comment by bensinjin** [comment]
@PeaceGeeksProjects please confirm and close.

**Comment by PeaceGeeksProjects** [comment]
Please move to Done Pipeline




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype**.* reneeontheroad
*pgp. *9253 3C6E 70B4 5211 6854 ED5E B585 C32D 264C 9CB6

**Comment by PeaceGeeksProjects** [comment]
@bensinjin the Logo fields are still there insted of the view for #799.
Moving back to In Progress.

**Comment by bensinjin** [comment]
@PeaceGeeksProjects This is what I've Implemented these buttons:
Manage Logo & Tagline ->  Site Name, Tagline, Logo
Manage Contact Page -> Address, Lat/Long, Email, Phone

Deployed to dev. Moving to Done.

**Comment by brandonq-appnovation** [comment]
Tested on Amani Zen Dev.

I have verified that the fields specified in the first comment have been added.

![pgks_manage_contact_settings](https://cloud.githubusercontent.com/assets/19274675/15196346/a0f1e30a-1780-11e6-9282-ce6da823e87b.png)

However, when the user tries to open "Convert your address", the modal that appears is just a blank white box with no functionality.

![pgks_convert_your_address](https://cloud.githubusercontent.com/assets/19274675/15196355/aa314960-1780-11e6-9ebd-f69101399b17.png)

Moving this back to "In Progress".

**Comment by bensinjin** [comment]
Hey @brandonq-appnovation I've implemented a fix although this url does not allow us to display their content in a modal (its iframe settings are too strict) so instead it'll open in a new tab.

**Comment by brandonq-appnovation** [comment]
Verified on Amani Zen Theme Dev site.

- In "Configure Amani", the "Manage Contact Page Settings" has a button link called "Manage Contact Settings".
- All of the fields specified in the original comment are under "Manage Contact Settings", and are editable. The edits successfully show up on the Contact page.
- Clicking "Convert your address" opens a new tab to "http://www.latlong.net/convert-address-to-lat-long.html". The user can copy the Latitude and Longitude information from this site into the setting.

Moving this into "QA".

**Comment by PeaceGeeksProjects** [comment]
Verifued on Dev & LYM
