### ISSUE TITLE
Re-export hompage blocks into features

### ISSUE THREAD

**Issue by nbosco** [PeaceGeeksSociety/amani#806]
Create footer image blocks, export into features.
Hook update for 'Image behind twitter block', export to features and update context.
Reorganize context and export.

**Comment by MagdiRizkallah** [comment]
I have no way of testing this.  @bensinjin can you verify and close this one?

**Comment by akochlan** [comment]
validated  dev http://dev.amani-zen-theme.peacegeeks.org/  on web desktop and mobile. Looks good.
![footer images](https://cloud.githubusercontent.com/assets/16566072/12177291/50007a5a-b539-11e5-8250-52078acc7196.png)

**Comment by akochlan** [comment]
Steps to reproduce:
1. Login as Amani Admin.
2. Select 'Configure Amani'
3. Select 'Manage Amani Bloks'
4. Select 'Manage Social Media Feeds ( home page )'
5.  Click on 'Enable Social Media Feeds'

**Comment by PeaceGeeksProjects** [comment]
@akochlan I do not understand how your test relate to the issue (exporting into features).  I am reassigning to the Amani team who can test and close.

**Comment by akochlan** [comment]
@PeaceGeeksProjects I am testing based on provided information: description and acceptance criteria.

**Comment by bensinjin** [comment]
I'm confused here - is this committed to the aman zen branch? can you point me to the commit?

**Comment by PeaceGeeksProjects** [comment]
@limage could you please reply to @bensinjin

**Comment by PeaceGeeks** [comment]
Can we close this @mackh

**Comment by PeaceGeeks** [comment]
Undefined issue. Closing.
