### ISSUE TITLE
Amani Zen- Home-Header Theming

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#817]
Amani -Home-Header

**Comment by PeaceGeeks** [comment]
https://drive.google.com/open?id=0B3VbDQ0s1eNLfjU3b1pNdVB4Ty1DdEVtN1lOVTZfLUcwY3dabHhtYW9peXFfWkRfMjVGWUE

**Comment by Rahims74** [comment]
If you have completed please submit the code.

**Comment by PeaceGeeks** [comment]
Looking good! Only thing missing is the tagline on Desktop

**Comment by PeaceGeeks** [comment]
Neither the logo nor the tagline should go in code - except maybe placeholders - something like 'your logo goes here' and 'your tagline goes here' - does that make sense? 

Also, I can see from the mocks that she had the tagline split on either side of the logo, but that won't work for some partners, so I suggest we place it below the logo.
