### ISSUE TITLE
AmaniZen -Map Theming

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#819]
Map Header
Footer
Logo

**Comment by PeaceGeeks** [comment]
https://drive.google.com/open?id=0B3VbDQ0s1eNLfkFUTXByV2RGcVpfTF9CcGh2WjZXWUZDcEd5NGhWR3NuUmlPUlpsLWdDVWc

**Comment by PeaceGeeks** [comment]
These are global features that are dealt with in other tickets.
