### ISSUE TITLE
Amani Zen-About

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#821]
Update Amani Zen -About

**Comment by PeaceGeeks** [comment]
About Page design 
https://drive.google.com/open?id=0B3VbDQ0s1eNLflJvN1VsTEd3amRGUmlZay1tR3puUEw3ZVNLcTJUN1YzZllVV2h0MEJjMGc

**Comment by PeaceGeeks** [comment]
@limage - The original designer for this page produced a new version unexpectedly (she had said she was not available to do so). In that case, please review the new version and Myles' comments to see if everything was captured. If that is the case, these can be approved and moved into the Productions folder.

I can see that the 'sub-about' elements (below the large image which should be smaller), should have a smaller image option so please make that change and send to us for approval.

**Comment by PeaceGeeks** [comment]
Hi @limage - this is the updated mock on invision. All correct and up-to-date mocks can be found there. https://projects.invisionapp.com/d/main#/console/4971962/111478499/preview

**Comment by PeaceGeeks** [comment]
See #956 for most recent info
