### ISSUE TITLE
Amani Zen About -Team

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#822]

**Comment by PeaceGeeks** [comment]
From Myles - I wouldn't use a new design pattern. I would re-use the "featured resource" UI element. It would save on development and look more consistent

Connect with Miles on feedback

Featured Resources can be viewed here: https://drive.google.com/a/appnovation.com/file/d/0B8yH9xedE0fybHRxX1JUTnhsMGM/view?usp=sharing

**Comment by PeaceGeeks** [comment]
Also from Myles
Myles O'Leary: If I were to be designing these pages, I would follow a similar format to Resource Node page. That layout restricts the line length which is important to combat "Reader Fatigue". The full width text layout doesn't allow users to casually read the information. They will struggle to get to the next line. As well, something about the photo of the person on the left doesn't feel right. It feels like an after though. It almost feels like a sidebar item that is not related to the content. Even moving it to the left in the same spot would be an improvement

**Comment by PeaceGeeks** [comment]
@limage - The original designer for this page produced a new version unexpectedly (she had said she was not available to do so). In that case, please review the new version and Myles' comments to see if everything was captured. If that is the case, these can be approved and moved into the Productions folder.
