### ISSUE TITLE
Amani Zen About -Image Gallery Design

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#823]

**Comment by Rahims74** [comment]
[2015-08-04, 11:50:40 AM] Myles O'Leary: Gallery: I would remove the bottom pink line. Its not necessary.

**Comment by PeaceGeeks** [comment]
https://drive.google.com/open?id=0B3VbDQ0s1eNLfjFFamE0cFFRWndOeDIyWjZVMGtlZnFGWTZCUWJHbUZENjlpaDFXLWY3NkU

**Comment by PeaceGeeks** [comment]
Also from Myles
Myles O'Leary: If I were to be designing these pages, I would follow a similar format to Resource Node page. That layout restricts the line length which is important to combat "Reader Fatigue". The full width text layout doesn't allow users to casually read the information. They will struggle to get to the next line. As well, something about the photo of the person on the left doesn't feel right. It feels like an after though. It almost feels like a sidebar item that is not related to the content. Even moving it to the left in the same spot would be an improvement

**Comment by PeaceGeeks** [comment]
Looks like the bottom line still needs to be removed. Please review for his other general comments.
