### ISSUE TITLE
Amani Zen About-Partners Design

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#824]

**Comment by Rahims74** [comment]
Myles O'Leary: If I were to be designing these pages, I would follow a similar format to Resource Node page. That layout restricts the line length which is important to combat "Reader Fatigue". The full width text layout doesn't allow users to casually read the information. They will struggle to get to the next line. As well, something about the photo of the person on the left doesn't feel right. It feels like an after though. It almost feels like a sidebar item that is not related to the content. Even moving it to the left in the same spot would be an improvement 

I am curious what is the "About  |  Team" item is at the top?

The "back to team" page feature may not be necessary. But, if you do wish to have a link for the user, it should be on the left and the arrow should point backwards. This feature is currently on the right with an arrow facing "forward". It doesn't compute with the brain logically. When we think of going back we don't think "right hand side with a right facing arrow". It just defies what our senses would expect.
[2015-08-04, 11:50:40 AM] Myles O'Leary: Gallery: I would remove the bottom pink line. Its not necessary.

Team: I wouldn't use a new design pattern. I would re-use the "featured resource" UI element. It would save on development and look more consistent
Connect with Miles on feedback

**Comment by PeaceGeeks** [comment]
Fix pager for mobile for Partners page
http://dev.amani-zen-theme.peacegeeks.org/partners?page=1

(wraps funny)
<img width="342" alt="screen shot 2015-11-12 at 6 10 35 pm" src="https://cloud.githubusercontent.com/assets/2263033/11137006/b7e22e90-8968-11e5-8a36-719964ff43bb.png">
