### ISSUE TITLE
Slideshow slides link always on

### ISSUE THREAD

**Issue by MagdiRizkallah** [PeaceGeeksSociety/amani#829]
Wether there is actually a link defined or not.  When any slide is clicked, you get the error:
Page not found
The requested page "/%5Bfield_link%5D" could not be found.

**Comment by PeaceGeeks** [comment]
When there is no URL, there should be no slider link

**Comment by jayappnovation** [comment]
Fixed and Pushed on bugfix/829-incorrect-style-for-title-in-slideshow branch
(The SCSS files need to be recompiled by a Front end and pushed again to this branch)

**Comment by PeaceGeeksProjects** [comment]
@bensinjin Please update the dev site (http://dev.amani-zen-theme.peacegeeks.org/) so I can test

**Comment by bensinjin** [comment]
I've pulled but nothing was in the Amani-Zen-Theme branch, I did however
notice origin/bugfix/829-incorrect-style-for-title-in-slideshow (a new
branch) please confirm this is the correct branch and I can merge it into
Amani-Zen-Theme or instruct whomever was working on this to do so.

**Comment by jayappnovation** [comment]
Hi,

please do not merge this branch
"origin/bugfix/829-incorrect-style-for-title-in-slideshow" on
"Amani-zen-theme" for the moment...

On Tue, Jan 5, 2016 at 3:44 PM, Ben St John <notifications@github.com>
wrote:

> I've pulled but nothing was in the Amani-Zen-Theme branch, I did however
> notice origin/bugfix/829-incorrect-style-for-title-in-slideshow (a new
> branch) please confirm this is the correct branch and I can merge it into
> Amani-Zen-Theme or instruct whomever was working on this to do so.
>
> On Tue, Jan 5, 2016 at 12:38 PM, PeaceGeeksProjects <
> notifications@github.com> wrote:
>
> > @bensinjin <https://github.com/bensinjin> Please update the dev site (
> > http://dev.amani-zen-theme.peacegeeks.org/) so I can test
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/PeaceGeeksSociety/amani/issues/829#issuecomment-169126191
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PeaceGeeksSociety/amani/issues/829#issuecomment-169127397>
> .
>



-- 
<http://email.appno.net/email-top.php>

Jerome Tchania
Drupal Developer

5455 de Gaspé Avenue, Suite 370
Montréal, QC, H2T 3B3 Canada
www.appnovation.com

<CASLunsubscribe@appnovation.com?subject=Unsubscribe&body=I%27m+sorry+to+hear+that+you+wish+to+unsubscribe,+just+send+this+message+and+we%27ll+remove+you.>
<http://email.appno.net/email-bottom.php>

**Comment by jayappnovation** [comment]
According my comment 2hours ago, a themer need to pull from this branch , compile all scss and push again to this branch. After that this branch could be merged on "Amani-Zen-Theme"

Thank you

**Comment by bensinjin** [comment]
Understood, thanks.

**Comment by bensinjin** [comment]
Fixed.

**Comment by brandonq-appnovation** [comment]
I have verified this on the dev site. Only slideshow links with a value in the "URL" field will link to a site when clicked.

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
