### ISSUE TITLE
Amani Zen-Footer Theming

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#832]
Please complete the Header for home. If this is complete please submit changes.

**Comment by PeaceGeeks** [comment]
https://drive.google.com/open?id=0B3VbDQ0s1eNLfjU3b1pNdVB4Ty1DdEVtN1lOVTZfLUcwY3dabHhtYW9peXFfWkRfMjVGWUE

**Comment by PeaceGeeks** [comment]
This is very close - just the spacing of the pg logo and text below the logo needs to be tweaked! https://projects.invisionapp.com/d/main#/console/4971962/110224363/preview

**Comment by PeaceGeeks** [comment]
See #937

**Comment by PeaceGeeks** [comment]
Contact and Login need to be adde to the footer.

**Comment by PeaceGeeks** [comment]
Contact now appear. We just need Login.

**Comment by bensinjin** [comment]
I don't have permission to view the invision pages - all I can see is https://drive.google.com/folderview?id=0B3VbDQ0s1eNLfjU3b1pNdVB4Ty1DdEVtN1lOVTZfLUcwY3dabHhtYW9peXFfWkRfMjVGWUE&usp=drive_web - I'm not clear on this little arrow is it like a dropdown?

**Comment by MagdiRizkallah** [comment]
Try this https://projects.invisionapp.com/share/KB4R6KBD9#/screens/110224363

**Comment by limage** [comment]
Home and Login item already there

**Comment by PeaceGeeksProjects** [comment]
@Li why did you think it is Done?
Invision https://projects.invisionapp.com/share/TR4QUJ3UY#/screens/110224363
Dev https://projects.invisionapp.com/share/TR4QUJ3UY#/screens/110224363 is missing the 2 Logos and has teh Donate Button?

**Comment by limage** [comment]
@PeaceGeeksProjects Are you mention missing 2 logos? but that's what I saw in dev site http://dev.amani-zen-theme.peacegeeks.org/
![screen shot 2016-05-02 at 9 44 06 am](https://cloud.githubusercontent.com/assets/5281717/14960823/62e6cb02-104b-11e6-9692-9b0f53b848d0.png)
The logos and missing "Home" and "Login" menu items already on the Footer menu, is right?

**Comment by PeaceGeeksProjects** [comment]
Tx @limage But the Logos disappear when you login...

**Comment by limage** [comment]
@PeaceGeeksProjects I login as "superadmin", the logos looks fine. may have some permission issue for some user?

**Comment by PeaceGeeksProjects** [comment]
@limage You may be right... I login as AmaniAdmin.  Logos should be visible to all users...

**Comment by PeaceGeeks** [comment]
Verified
