### ISSUE TITLE
Amani Zen-Slideshow Theming

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#833]

**Comment by Rahims74** [comment]
https://drive.google.com/open?id=0B3VbDQ0s1eNLfjU3b1pNdVB4Ty1DdEVtN1lOVTZfLUcwY3dabHhtYW9peXFfWkRfMjVGWUE

**Comment by PeaceGeeks** [comment]
The arrows need to be more visible - needs a higher contrast between the arrow and background color.

**Comment by bensinjin** [comment]
The arrows are currently images - please provide new images or some example of how this should look.

**Comment by MagdiRizkallah** [comment]
@PeaceGeeks I do not see any navigation arrows now.  What should that look like?  Also specify the default slide time, now it is not looping through them...

**Comment by limage** [comment]
@PeaceGeeks Navigation arrows only display for more than one slide image, just don't forget to check publish option

**Comment by PeaceGeeksProjects** [comment]
Tx @limage however, now that there are more than 1 published slideshow images, I still cannot see the navigation arrows.  Moving back to In Progress
![zen833a](https://cloud.githubusercontent.com/assets/16202351/14652562/ae71335e-0629-11e6-8153-a5a004de7f87.JPG)
![zen833b](https://cloud.githubusercontent.com/assets/16202351/14652561/ae6de442-0629-11e6-880b-e9bf472a3f11.JPG)

**Comment by limage** [comment]
@PeaceGeeksProjects  There are arrows under the gray button, maybe we need to modify the color to make it more contrast?

**Comment by PeaceGeeksProjects** [comment]
Tx @limage I can see them now... moving to Done

**Comment by appnoviv** [comment]
@limage - The slide image seems to be stretched after adding a new one.  Please take a look.

**Comment by PeaceGeeksProjects** [comment]
@limage - May be the original size does matter?  What should it be?

**Comment by limage** [comment]
@PeaceGeeksProjects The original image was just too large (7500 x 4500)  Optimal size should be half of that.  There is a technical issue with Drupal where it takes time to process the large images and display it properly.

**Comment by PeaceGeeksProjects** [comment]
We need to accurately document the optimal image sizes.  See #581

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev & LYM
