### ISSUE TITLE
Amani Zen- Background Images

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#834]
https://drive.google.com/open?id=0B3VbDQ0s1eNLfjU3b1pNdVB4Ty1DdEVtN1lOVTZfLUcwY3dabHhtYW9peXFfWkRfMjVGWUE

**Comment by PeaceGeeksProjects** [comment]
@PeaceGeeks do you know what this is about?

**Comment by PeaceGeeks** [comment]
Yes it is the background image on the home page design which is in place so closing.
