### ISSUE TITLE
Create Featured flag for Resources

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#872]

**Comment by PeaceGeeks** [comment]
@jayappnovation - can you see if this is already in code?

**Comment by akochlan** [comment]
Q: Is "Create Featured" flag same as "Featured resources" flag?, see screenshot
![featured resources](https://cloud.githubusercontent.com/assets/16566072/12175875/93440946-b532-11e5-8fb6-6be97251d655.png)

**Comment by jayappnovation** [comment]
@akochlan Yes it is

**Comment by akochlan** [comment]
Then, this ticket is verified and passed.

**Comment by PeaceGeeks** [comment]
Featured flag verified
