### ISSUE TITLE
About-Team

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#884]

**Comment by PeaceGeeks** [comment]
http://dev.amani-zen-theme.peacegeeks.org/team - This is mostly looking fine but why does the bottom row spread the two records the full width? They should all be the same size.

**Comment by PeaceGeeks** [comment]
Also the filters seem to work, but the images should align from the left, not from the right

**Comment by PeaceGeeks** [comment]
Also the, 'path' is the wrong color

**Comment by limage** [comment]
Fixed align to the left, and Safari bugs
