### ISSUE TITLE
AmaniZen- About-Image Gallery

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#885]

**Comment by PeaceGeeks** [comment]
Looking good but the second 'Galleries' in blue should be removed.
<img width="833" alt="screen shot 2015-10-01 at 5 18 55 pm" src="https://cloud.githubusercontent.com/assets/2263033/10236916/95c1239e-6860-11e5-9a5f-4840b6b604f2.png">

**Comment by PeaceGeeks** [comment]
Adjust the image dimensions according to the mocks. Also add the date, # of photos and date as per the mock. https://invis.io/PK4X5I9EY

**Comment by limage** [comment]
Can't make feature export of  image style, you have change "gallery-image-thumbnail" from 450X450 to 450X300 by manually, need clean image cache too

**Comment by PeaceGeeks** [comment]
@limage - can clarify your comments above?

**Comment by PeaceGeeks** [comment]
@limage - can you quickly comment on this ticket, so we are clear on what needs to be done here?

**Comment by PeaceGeeks** [comment]
@bensinjin - I think we need your input on this. Li is not sure if we should define in code or export the image style like feature. Can you comment?

**Comment by bensinjin** [comment]
I'm not sure I see what's wrong with this?

**Comment by PeaceGeeks** [comment]
Ok let's close.
