### ISSUE TITLE
AmaniZen-About-Partners

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#886]

**Comment by PeaceGeeks** [comment]
Fix pager for mobile for Partners page - only seems to be an issue when on a page other than 1. Also, users should be able to click on pager numbers.

http://dev.amani-zen-theme.peacegeeks.org/partners?page=1

(wraps funny)
<img width="342" alt="screen shot 2015-11-12 at 6 10 35 pm" src="https://cloud.githubusercontent.com/assets/2263033/11160062/550a5b28-8a1a-11e5-8f48-f53aa6627984.png">

**Comment by limage** [comment]
fixed

**Comment by limage** [comment]
Fixed before, need QA!

**Comment by akochlan** [comment]
Validated on mobile: Samsung Galaxy, Chrome. Not sure what you mean "Fix pager".  Can not see pager number even on page 1. Please, clarify.

**Comment by PeaceGeeksProjects** [comment]
Pager works fine on iPhone
