### ISSUE TITLE
AmaniZen-Programs

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#887]

**Comment by limage** [comment]
https://lh4.googleusercontent.com/qqdL6IRrVg2Ma7MF3O4pJT-j0qRlVsZuGX3U4BFK01_ng0S_ieSUqKCrYSR5GbMv1frBpq6RsQDA8zor6XL1O_31_BY=w1412-h1153

Is this right mock up of above link? if so, please add content list of sidebar to instead of images.
http://dev.amani-zen-theme.peacegeeks.org/programs

**Comment by PeaceGeeks** [comment]
Hi Li - the link above does not work?

**Comment by PeaceGeeks** [comment]
Also, I can't open this link either?

**Comment by PeaceGeeks** [comment]
There are two version of the Programs page. One version has 2 columns plus sidebar, another version has 3 columns and no sidebar. @bensinjin - can you remind us how this works in Amani right now? I believe this is just done by hiding the 'Get Involved' block?
