### ISSUE TITLE
AmaniZen-Program/Activity

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#888]

**Comment by PeaceGeeks** [comment]
Theme for Activity node to be adjusted for color and 'back' option so that it is consistent with Michelle 'Activity' mock. https://invis.io/TR4QUJ3UY

**Comment by limage** [comment]
Done! theming code in Amani-Zen-Theme branch

**Comment by akochlan** [comment]
Validated on dev: http://dev.amani-zen-theme.peacegeeks.org/programs. Colour matched . What is 'back' option? Activity node doesn't match mockup https://invis.io/TR4QUJ3UY. 
@PeaceGeeks Please, provide more details.

**Comment by akochlan** [comment]
@PeaceGeeks Please, disregard my previous message. Wrong page was verified. Activity page http://dev.amani-zen-theme.peacegeeks.org/activity/nepal match mockup except missed OTHER section.

**Comment by akochlan** [comment]
@PeaceGeeks Please, disregard previous comment. Activity node http://dev.amani-zen-theme.peacegeeks.org/activity/nepal matched mockups, except missed section OTHER PROGRAMS.

**Comment by akochlan** [comment]
Story verified. Passed.

**Comment by PeaceGeeksProjects** [comment]
OTHER PROGRAMS should not show on activity detail view...  All good.
