### ISSUE TITLE
AmaniZen-Resouces

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#891]

**Comment by limage** [comment]
we need someone to separate section of Feature Resources and All Resources, also image of feature resource block is missing.
https://lh6.googleusercontent.com/YFwdy5aY5KF6sj-yyRV15fbqAxHWhLMadgAGGNhSNTIPnpZbavv012XMtaSD8tlcMb3xrvxrIfiQk_vMaoc5qPrNzTQ=w1412-h1153
