### ISSUE TITLE
AmaniZen-Map

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#899]
Map-Turn to an infinite scroll (for mobile and desktop.
Remove Arrows after text in buttons seem to appear somewhat randomly throughout the site.

**Comment by limage** [comment]
1. tweaked resource-map page and made it responsive version.
2. add autopage js, you have change to "infinite scroll" in view setting when you going to turn on this function, but the feature of infinite scroll work in finicky way, may needs back end people to take a look.
