### ISSUE TITLE
AmaniZen-Program/Activity(Desktop)

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#912]

**Comment by limage** [comment]
Done with mobile version too!

**Comment by PeaceGeeks** [comment]
Sidebar seem to be missing! http://dev.amani-zen-theme.peacegeeks.org/activity/geting-jiggy-it

**Comment by limage** [comment]
Sidebar there now.

**Comment by akochlan** [comment]
Validated on dev http://dev.amani-zen-theme.peacegeeks.org/activity/democratic-republic-conon-drc. OTHER ACTIVITY side bar is added. OTHER PROGRAMS side bas is missed. Failed.

**Comment by limage** [comment]
Please assign to back end for missing OTHER PROGRAMS block!

**Comment by PeaceGeeksProjects** [comment]
OTHER PROGRAMS block is not supposed to appear on Activity Detail view.  No re-assignment needed
