### ISSUE TITLE
AmaniZen-Header-SubNav

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#927]
When you hover over the menu the subnav does not oppear

**Comment by limage** [comment]
The javascript of footerThreeColumns effect this function, I have commented out.
Plesae check the checkbox of Show as expanded(ex: http://dev.amani-zen-theme.peacegeeks.org/admin/structure/menu/item/657/edit ) after Amani-Zen-Theme branch merge to dev site.

**Comment by limage** [comment]
Done!
