### ISSUE TITLE
AmaniZen-Footer Update

### ISSUE THREAD

**Issue by Rahims74** [PeaceGeeksSociety/amani#936]
Update Footer across pages to match Styleguide.
https://app.frontify.com/document/35623

**Comment by bensinjin** [comment]
@PeaceGeeksProjects @Rahims74 I don't have permission to see this, please invite me my email is ben@affinitybridge.com.

**Comment by PeaceGeeksProjects** [comment]
To see what?




*Renee Black*,
*Executive Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
*p.* 778-235-7458 | *e.* renee@peacegeeks.org
*skype**.* reneeontheroad
*pgp. *9253 3C6E 70B4 5211 6854 ED5E B585 C32D 264C 9CB6

**Comment by MagdiRizkallah** [comment]
Undefined Issue , Closing
