### ISSUE TITLE
Tweak Contact page

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#943]
- remove purple background in fields
- make active fields border colored with #513D79 
- Send button should be aligned left
- Map should be themed according to the mock size
- Entire page should be themed according to the mock size
- Icons to be updated according to the style guides and icon library

**Comment by zetagraph** [comment]
Updates to "Contact" page commit: 197a141

- remove purple background in fields
- made active fields border colored #513D79
- send button aligned left

@PeaceGeeks 
Can we move updates to icons into a separate task as the whole icon font needs to be updated across the whole site.

**Comment by zetagraph** [comment]
@PeaceGeeks icons on Contact pages as well as globally are updated now.
