### ISSUE TITLE
Style News & Events landing page according to mock

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#945]

**Comment by PeaceGeeks** [comment]
Please note and address the comments on the mocks

https://projects.invisionapp.com/d/main#/console/4971962/113573704/preview

spacing for copy and 'Read more' should be consistent with style guide

**Comment by PeaceGeeksProjects** [comment]
Uase this link for invision without needing an account https://projects.invisionapp.com/share/TR4QUJ3UY#/screens/116357094

**Comment by limage** [comment]
'Read more' ? looks fine for me compare to invision mock-up @erica-scott can you double check it?

**Comment by dannyzoujx** [comment]
verified on dev (http://dev.amani-zen-theme.peacegeeks.org/news-and-events)

**Comment by MagdiRizkallah** [comment]
Confirmed
