### ISSUE TITLE
Map page to be tweaked

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#947]
'About violation' need vertical padding similar to first filter
Map too big - user can scroll down page because on 13", the map takes up the whole screen
Header title should be all caps and colored according to style guide H1
https://app.frontify.com/document/35623

**Comment by limage** [comment]
The title according to mock https://projects.invisionapp.com/share/KB4R6KBD9#/screens/107296948
better keep it as H2
