### ISSUE TITLE
Theme 'Blog' desktop and mobile landing page

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#969]
Desktop
https://projects.invisionapp.com/d/main#/console/4971962/113516652/preview

Mobile
https://projects.invisionapp.com/d/main#/console/4971962/113574969/preview

**Comment by limage** [comment]
https://github.com/PeaceGeeksSociety/amani/pull/1087 
@bensinjin please merge to dev and revert feature of "amani_blog" and "amani_event", thanks!
missing sidebar block "Blog Categories" and "Blog Tags",
also missing Author of Blog, please assign to back end people, thanks!

**Comment by bensinjin** [comment]
I think we're good here right?

**Comment by mackh** [comment]
Magdi can you please clarify if this is done now?

**Comment by PeaceGeeksProjects** [comment]
Blog page should look as designed
Desktop: https://projects.invisionapp.com/share/TR4QUJ3UY#/screens/116353704
Mobile: https://projects.invisionapp.com/share/TR4QUJ3UY#/screens/116353715

**Comment by limage** [comment]
Need back end people to enable Blog Categories block and Blog Tags Block

**Comment by PeaceGeeksProjects** [comment]
@bensinjin Help please!

**Comment by bensinjin** [comment]
@PeaceGeeksProjects I can't see the designs anymore - says they may been deleted? Anyways I believe this was addressed in https://github.com/PeaceGeeksSociety/amani/issues/1192 I'm moving to done.

**Comment by PeaceGeeksProjects** [comment]
Agreed Closing
