### ISSUE TITLE
Finish theming Resources page for mobile

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#971]
Increase spacing between columns (roughly half the vertical space between different 'resources')

http://dev.amani-zen-theme.peacegeeks.org/resources

use desktop theme on dev as a guide

**Comment by PeaceGeeks** [comment]
Also, there are fields missing from each previous item AND the 'Featured' items are not appearing.

**Comment by limage** [comment]
Done! add filter toggle function for mobile version
https://github.com/PeaceGeeksSociety/amani/pull/1070

**Comment by akochlan** [comment]
Validated on mobile: Android/Chrome, iPhone/Safari, iPad. Looks good including labels and Filter toggle func. Not sure what fields are missing that were mentioned above.

**Comment by akochlan** [comment]
Missed download links but i's  known issue and mentioned in another ticket.

**Comment by PeaceGeeksProjects** [comment]
Verified theme.  missing download is #1052
