### ISSUE TITLE
Home page tweaks 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#972]
On home, month in calendar block should be same size as  year
<img width="280" alt="screen shot 2015-11-09 at 9 05 31 pm" src="https://cloud.githubusercontent.com/assets/2263033/11054867/c62cd0bc-8725-11e5-951a-5cb1d77547a2.png">

Article space needs to be fixes

Remove blue 'more' link in bottom right (not supposed there)

'News' headings are supposed to be all caps and bold

**Comment by limage** [comment]
Done!
