### ISSUE TITLE
Remove images from 'Get Involved' sidebar on 2-col version of Programs

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#976]
http://dev.amani-zen-theme.peacegeeks.org/programs

Remove images from 'Get Involved' sidebar on 2-col version of Programs - as per the design. https://projects.invisionapp.com/d/main#/console/4971962/107296860/preview

**Comment by limage** [comment]
Still working on it

**Comment by limage** [comment]
I think already removed, please double check.

**Comment by akochlan** [comment]
Validated on dev http://dev.amani-zen-theme.peacegeeks.org/programs. No more images on sidebar. Passed.

**Comment by PeaceGeeksProjects** [comment]
verified.
