### ISSUE TITLE
Tweak 'About' page based on revised mock

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#981]
'Our goals' section to be removed (no full width elements) - see the following mock
https://invis.io/G34X5HQ7D

Also, how did you theme it that way?

**Comment by limage** [comment]
Done it before.
http://dev.amani-zen-theme.peacegeeks.org/about

**Comment by akochlan** [comment]
Validated on dev http://dev.amani-zen-theme.peacegeeks.org/

Layout of 'Our Goal' section has been changed to match mockups. Passed.

**Comment by PeaceGeeksProjects** [comment]
Verified
