### ISSUE TITLE
Image gallery images look pixelated and needs to be designed according to mock

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#982]
Also seem to be the wrong dimension according to the mock
http://dev.amani-zen-theme.peacegeeks.org/galleries/16-days-activism

https://projects.invisionapp.com/d/#/console/4971962/107296651/preview

Ignore differences in the header. The live site is correct.

**Comment by limage** [comment]
http://dev.amani-zen-theme.peacegeeks.org/galleries/16-days-activism
looks fine! you can upload better quality image to replace them.

**Comment by akochlan** [comment]
Validated on dev env. Image gallery designed according to mockup. Passed.

**Comment by PeaceGeeksProjects** [comment]
Verified
