### ISSUE TITLE
Map node page theming needs fixing

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#984]
http://dev.amani-zen-theme.peacegeeks.org/incident-report/gunmen-shoot-man-jubas-nyakuron

**Comment by limage** [comment]
Done! committed to Amani-zen-theme branch, but the map looks broken on node page

**Comment by limage** [comment]
map looks broken

**Comment by limage** [comment]
Fixed! https://github.com/PeaceGeeksSociety/amani/pull/1182
@bensinjin Please update dev site from Amani-Zen-Theme branch, thanks!

**Comment by PeaceGeeksProjects** [comment]
Verified on Dev
