### ISSUE TITLE
Partner node link should be consistent with color palette

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#993]
http://dev.amani-zen-theme.peacegeeks.org/content/peacegeeks

**Comment by limage** [comment]
Done!

**Comment by akochlan** [comment]
@MagdiRizkallah Could you clarify issue in this ticket, please? Thanks

**Comment by PeaceGeeksProjects** [comment]
Looks good to me according to https://projects.invisionapp.com/share/TR4QUJ3UY#/screens/107296725
