### ISSUE TITLE
Create view for Events page - Backend

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/amani#999]
See mock-ups for Events Landing page on Invision
https://projects.invisionapp.com/share/KB4R6KBD9#/screens/116357094

**Comment by jayappnovation** [comment]
Backend done, front end needed

**Comment by PeaceGeeks** [comment]
This button currently points back to the News & Events landing page. We need to theme the Events page.

**Comment by PeaceGeeksProjects** [comment]
Already Done.
